//! `GoalFile` → `.ax` source emission.
//!
//! Phase-10 v0: emits a scaffolded `.ax` artifact with verify gate +
//! function signatures derived from the prose.  Body sections are
//! `TODO:` placeholders — the author fills them in until later
//! phases ship LLM-driven body generation.

use crate::parser::GoalFile;
use crate::Result;
use std::fmt::Write;

pub fn emit(goal: &GoalFile) -> Result<String> {
    let mut out = String::new();

    // ── File header ────────────────────────────────────────────
    let _ = writeln!(out, "// {}", goal.title);
    let _ = writeln!(out, "//");
    let _ = writeln!(out, "// Generated by axon-surface from the structured-prose goal file.");
    let _ = writeln!(out, "// Intent + verify gate are derived from the prose. Function bodies are");
    let _ = writeln!(out, "// lifted from the goal file's ```axon blocks where present, and stubbed");
    let _ = writeln!(out, "// with `TODO:` placeholders where absent.");
    let _ = writeln!(out, "//");
    if let Some(intent) = goal.section("Intent") {
        for line in intent.body.lines().take(10) {
            let _ = writeln!(out, "// {line}");
        }
    }
    let _ = writeln!(out);

    // ── Inputs / Outputs → fn signatures for any scaffolded helpers ──
    let inputs = goal.inputs()?;
    let outputs = goal.outputs()?;
    let inputs_arg_ty = inputs
        .first()
        .map(|(_, ty)| ty.clone())
        .unwrap_or_else(|| "str".into());
    let inputs_arg_name = inputs
        .first()
        .map(|(name, _)| name.clone())
        .unwrap_or_else(|| "input".into());
    let output_arg = outputs
        .first()
        .map(|(name, ty)| format!("{name}: {ty}"))
        .unwrap_or_else(|| "output: str".into());

    // ── Author-supplied bodies (lifted from the goal file's ```axon blocks) ──
    // Each helper the author defines in prose is emitted verbatim; only the
    // helpers they omit fall back to TODO: scaffolding.
    let author = goal.author_code();
    let provides = |name: &str| author.contains(&format!("fn {name}("));
    if !author.is_empty() {
        let _ = writeln!(out, "// ── Author-supplied (lifted from the goal file's ```axon blocks) ──");
        let _ = writeln!(out, "{author}");
        let _ = writeln!(out);
    }

    // The scaffolded helpers below exist only to feed the default `try_variant`
    // loop; if the author supplies their own `try_variant`, none are needed.
    let default_loop = !provides("try_variant");

    // ── Scaffold: test set ───────────────────────────────────────
    if default_loop && !provides("test_input") {
        let _ = writeln!(out, "// ── Scaffold: test set ───────────────────────────────────");
        let _ = writeln!(out, "// TODO: fill in N concrete test cases (3-5 typical, 1-2 adversarial).");
        let _ = writeln!(out, "fn test_input(i: i64) -> {inputs_arg_ty} {{");
        let _ = writeln!(out, "    if i == 0 {{");
        let _ = writeln!(out, "        \"TODO: first test case\"");
        let _ = writeln!(out, "    }} else if i == 1 {{");
        let _ = writeln!(out, "        \"TODO: second test case\"");
        let _ = writeln!(out, "    }} else {{");
        let _ = writeln!(out, "        adversarial_input()");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }
    if default_loop && !provides("adversarial_input") {
        let _ = writeln!(out, "fn adversarial_input() -> {inputs_arg_ty} {{");
        let _ = writeln!(out, "    // TODO: hallucination-bait / prompt-injection / edge-case input.");
        let _ = writeln!(out, "    \"TODO\"");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Scaffold: candidate generation ───────────────────────────
    if default_loop && !provides("build_prompt") {
        let _ = writeln!(out, "// ── Scaffold: candidate generation ───────────────────────");
        let _ = writeln!(out, "// TODO: enumerate 4-8 distinct prompt-prefix variants to compare.");
        let _ = writeln!(out, "fn build_prompt(variant_id: i64) -> str {{");
        let _ = writeln!(out, "    let v = variant_id % 4");
        let _ = writeln!(out, "    let v2 = if v < 0 {{ v + 4 }} else {{ v }}");
        let _ = writeln!(out, "    if v2 == 0 {{");
        let _ = writeln!(out, "        \"TODO: prompt variant 0. Input: \"");
        let _ = writeln!(out, "    }} else if v2 == 1 {{");
        let _ = writeln!(out, "        \"TODO: prompt variant 1. Input: \"");
        let _ = writeln!(out, "    }} else if v2 == 2 {{");
        let _ = writeln!(out, "        \"TODO: prompt variant 2. Input: \"");
        let _ = writeln!(out, "    }} else {{");
        let _ = writeln!(out, "        \"TODO: prompt variant 3. Input: \"");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Scaffold: score function ─────────────────────────────────
    if default_loop && !provides("score_output") {
        let _ = writeln!(out, "// ── Scaffold: score function ─────────────────────────────");
        let _ = writeln!(out, "// TODO: implement the score formula from the Score section (0..100).");
        let _ = writeln!(out, "fn score_output({inputs_arg_name}: {inputs_arg_ty}, {output_arg}) -> i64 {{");
        let _ = writeln!(out, "    0");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Hill-climb target ────────────────────────────────────────
    // The author may supply their own `@[adaptive] fn try_variant(i64) -> i64`
    // in a prose ```axon block (full control over the goal loop). Otherwise we
    // emit the default LLM-driven loop over prompt variants + test cases.
    if !provides("try_variant") {
        let _ = writeln!(out, "// ── Hill-climb target — driven by goal_run ───────────────");
        let _ = writeln!(out, "@[adaptive]");
        let _ = writeln!(out, "fn try_variant(variant_id: i64) -> i64 {{");
        let _ = writeln!(out, "    let prompt = build_prompt(variant_id)");
        let _ = writeln!(out, "    let total = 0");
        let _ = writeln!(out, "    let i = 0");
        let _ = writeln!(out, "    while i < 2 {{");
        let _ = writeln!(out, "        let inp = test_input(i)");
        let _ = writeln!(out, "        let full = \"{{prompt}}{{inp}}\"");
        let _ = writeln!(out, "        match ai_complete(full) {{");
        let _ = writeln!(out, "            Ok(reply) => {{ total = total + score_output(inp, reply) }}");
        let _ = writeln!(out, "            Err(_) => {{}}");
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "        i = i + 1");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "    total / 2");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Verify gate ──────────────────────────────────────────────
    // The prose predicate may be richer than Axon's v0 verify form
    // (`<metric> OP <number>`), so preserve it verbatim as a comment and emit
    // a valid `score`-threshold gate the skeleton can actually compile and run.
    let predicate = goal.verify_predicate()?;
    let target = extract_target_from_predicate(&predicate).unwrap_or(70);
    // The author may supply their own `assert_deployable` (e.g. a confidence-
    // returning gate that the runtime `@[verify]` check actually enforces).
    // Otherwise emit a pass-through gate carrying the prose predicate's threshold.
    if !provides("assert_deployable") {
        let _ = writeln!(out, "// ── Verify gate (derived from prose) ──────────────────────");
        let _ = writeln!(out, "// prose predicate: {predicate}");
        let _ = writeln!(out, "@[verify(score >= {target})]");
        let _ = writeln!(out, "fn assert_deployable(score: i64) -> i64 {{");
        let _ = writeln!(out, "    score");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Main ─────────────────────────────────────────────────────
    let _ = writeln!(out, "// ── Main loop ────────────────────────────────────────────");
    let _ = writeln!(out, "fn main() -> i64 {{");
    let _ = writeln!(out, "    println(\"goal: {} — searching variants...\")", goal.title);
    // goal_run drives the @[adaptive] try_variant (hill-climbing variant_id).
    // Its target is an f64; the result is converted back to i64 for the gate.
    let _ = writeln!(out, "    let result = goal_run(\"try_variant\", {target}.0, 20)");
    let _ = writeln!(out, "    let best = f64_to_i64(result)");
    let _ = writeln!(out, "    println(\"best score: {{to_str(best)}} (target {target})\")");
    let _ = writeln!(out, "    let _ = assert_deployable(best)");
    let _ = writeln!(out, "    println(\"deploy gate: passed\")");
    let _ = writeln!(out, "    0");
    let _ = writeln!(out, "}}");

    Ok(out)
}

/// Try to pull a numeric threshold out of a verify predicate.
/// E.g., "score >= 70" → 70; "confidence >= 0.9" → can't (float, fallback).
fn extract_target_from_predicate(p: &str) -> Option<i64> {
    for tok in p.split_whitespace() {
        if let Ok(n) = tok.parse::<i64>() {
            return Some(n);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::GoalFile;

    const SAMPLE: &str = r#"# Goal: Test sample

## Intent

Do a thing.

## Inputs

- `text: str` — input.

## Outputs

- `summary: str` — output.

## Score (higher is better)

Some scoring.

## Constraints

- A constraint.

## Budget

- 100 calls.

## Verify

```axon
@[verify(score >= 70)]
```

## Redteam

- Some adversarial test.

## Effect surface

- Just LLM calls.

## Provenance

- JSONL log.
"#;

    #[test]
    fn emits_compileable_skeleton() {
        let g = GoalFile::parse(SAMPLE).unwrap();
        let ax = emit(&g).unwrap();
        // Header.
        assert!(ax.starts_with("// Goal: Test sample"));
        // Verify gate carried through (score-threshold form derived from prose).
        assert!(ax.contains("@[verify(score >= 70)]"));
        // Prose predicate preserved as a comment.
        assert!(ax.contains("// prose predicate: score >= 70"));
        // Function signature uses input type from prose.
        assert!(ax.contains("fn test_input(i: i64) -> str"));
        // Goal_run drives the adaptive try_variant with an f64 target.
        assert!(ax.contains("goal_run(\"try_variant\", 70.0, 20)"));
        // Adaptive annotation present.
        assert!(ax.contains("@[adaptive]"));
        // Build_prompt present.
        assert!(ax.contains("fn build_prompt(variant_id: i64) -> str"));
        // With no author code blocks, the score scaffold is emitted.
        assert!(ax.contains("// TODO: implement the score formula"));
    }

    #[test]
    fn lifts_author_bodies_and_drops_scaffold() {
        // SAMPLE plus an Implementation section that supplies score_output.
        let md = format!(
            "{SAMPLE}\n## Implementation\n\n```axon\n\
             fn score_output(text: str, summary: str) -> i64 {{ len(summary) }}\n```\n"
        );
        let g = GoalFile::parse(&md).unwrap();
        let ax = emit(&g).unwrap();
        // Author body lifted verbatim.
        assert!(ax.contains("// ── Author-supplied"));
        assert!(ax.contains("fn score_output(text: str, summary: str) -> i64 { len(summary) }"));
        // The provided helper's scaffold is dropped...
        assert!(!ax.contains("// TODO: implement the score formula"));
        // ...but unprovided helpers still get scaffolds.
        assert!(ax.contains("fn build_prompt(variant_id: i64) -> str"));
        assert!(ax.contains("fn test_input(i: i64) -> str"));
    }
}
