//! `GoalFile` → `.ax` source emission.
//!
//! Phase-10 v0: emits a scaffolded `.ax` artifact with verify gate +
//! function signatures derived from the prose.  Body sections are
//! `TODO:` placeholders — the author fills them in until later
//! phases ship LLM-driven body generation.

use crate::parser::GoalFile;
use crate::Result;
use std::fmt::Write;

/// Reusable goal-scoring helpers, auto-included on demand (see [`prelude_fns`]).
const PRELUDE_SRC: &str = include_str!("prelude.ax");

pub fn emit(goal: &GoalFile) -> Result<String> {
    let mut out = String::new();

    // ── File header ────────────────────────────────────────────
    let _ = writeln!(out, "// {}", goal.title);
    let _ = writeln!(out, "//");
    let _ = writeln!(out, "// Generated by axon-surface from the structured-prose goal file.");
    let _ = writeln!(out, "// Intent + verify gate are derived from the prose. Function bodies are");
    let _ = writeln!(out, "// lifted from the goal file's ```axon blocks where present, and stubbed");
    let _ = writeln!(out, "// with `TODO:` placeholders where absent.");
    let _ = writeln!(out, "//");
    if let Some(intent) = goal.section("Intent") {
        for line in intent.body.lines().take(10) {
            let _ = writeln!(out, "// {line}");
        }
    }
    let _ = writeln!(out);

    // ── Inputs / Outputs → fn signatures for any scaffolded helpers ──
    let inputs = goal.inputs()?;
    let outputs = goal.outputs()?;
    let inputs_arg_ty = inputs
        .first()
        .map(|(_, ty)| ty.clone())
        .unwrap_or_else(|| "str".into());
    let inputs_arg_name = inputs
        .first()
        .map(|(name, _)| name.clone())
        .unwrap_or_else(|| "input".into());
    let output_arg = outputs
        .first()
        .map(|(name, ty)| format!("{name}: {ty}"))
        .unwrap_or_else(|| "output: str".into());

    // ── Author-supplied bodies (lifted from the goal file's ```axon blocks) ──
    // Each helper the author defines in prose is emitted verbatim; only the
    // helpers they omit fall back to TODO: scaffolding.
    let author = goal.author_code();
    let provides = |name: &str| author.contains(&format!("fn {name}("));

    // Auto-include prelude helpers the goal references but doesn't itself define.
    // Each prelude fn is self-contained, so a direct-reference filter is enough.
    let used_prelude: Vec<(String, String)> = prelude_fns()
        .into_iter()
        .filter(|(name, _)| {
            author.contains(&format!("{name}(")) && !author.contains(&format!("fn {name}("))
        })
        .collect();
    if !used_prelude.is_empty() {
        let _ = writeln!(out, "// ── Prelude (auto-included helpers the goal references) ──");
        for (_, def) in &used_prelude {
            let _ = writeln!(out, "{def}");
            let _ = writeln!(out);
        }
    }

    if !author.is_empty() {
        let _ = writeln!(out, "// ── Author-supplied (lifted from the goal file's ```axon blocks) ──");
        let _ = writeln!(out, "{author}");
        let _ = writeln!(out);
    }

    // The scaffolded helpers below exist only to feed the default `try_variant`
    // loop; if the author supplies their own `try_variant`, none are needed.
    let default_loop = !provides("try_variant");

    // ── Scaffold: test set ───────────────────────────────────────
    if default_loop && !provides("test_input") {
        let _ = writeln!(out, "// ── Scaffold: test set ───────────────────────────────────");
        let _ = writeln!(out, "// TODO: fill in N concrete test cases (3-5 typical, 1-2 adversarial).");
        let _ = writeln!(out, "fn test_input(i: i64) -> {inputs_arg_ty} {{");
        let _ = writeln!(out, "    if i == 0 {{");
        let _ = writeln!(out, "        \"TODO: first test case\"");
        let _ = writeln!(out, "    }} else if i == 1 {{");
        let _ = writeln!(out, "        \"TODO: second test case\"");
        let _ = writeln!(out, "    }} else {{");
        let _ = writeln!(out, "        adversarial_input()");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }
    if default_loop && !provides("adversarial_input") {
        let _ = writeln!(out, "fn adversarial_input() -> {inputs_arg_ty} {{");
        let _ = writeln!(out, "    // TODO: hallucination-bait / prompt-injection / edge-case input.");
        let _ = writeln!(out, "    \"TODO\"");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Scaffold: candidate generation ───────────────────────────
    if default_loop && !provides("build_prompt") {
        let _ = writeln!(out, "// ── Scaffold: candidate generation ───────────────────────");
        let _ = writeln!(out, "// TODO: enumerate 4-8 distinct prompt-prefix variants to compare.");
        let _ = writeln!(out, "fn build_prompt(variant_id: i64) -> str {{");
        let _ = writeln!(out, "    let v = variant_id % 4");
        let _ = writeln!(out, "    let v2 = if v < 0 {{ v + 4 }} else {{ v }}");
        let _ = writeln!(out, "    if v2 == 0 {{");
        let _ = writeln!(out, "        \"TODO: prompt variant 0. Input: \"");
        let _ = writeln!(out, "    }} else if v2 == 1 {{");
        let _ = writeln!(out, "        \"TODO: prompt variant 1. Input: \"");
        let _ = writeln!(out, "    }} else if v2 == 2 {{");
        let _ = writeln!(out, "        \"TODO: prompt variant 2. Input: \"");
        let _ = writeln!(out, "    }} else {{");
        let _ = writeln!(out, "        \"TODO: prompt variant 3. Input: \"");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Scaffold: score function ─────────────────────────────────
    if default_loop && !provides("score_output") {
        let _ = writeln!(out, "// ── Scaffold: score function ─────────────────────────────");
        let _ = writeln!(out, "// TODO: implement the score formula from the Score section (0..100).");
        let _ = writeln!(out, "fn score_output({inputs_arg_name}: {inputs_arg_ty}, {output_arg}) -> i64 {{");
        let _ = writeln!(out, "    0");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Hill-climb target ────────────────────────────────────────
    // The author may supply their own `@[adaptive] fn try_variant(i64) -> i64`
    // in a prose ```axon block (full control over the goal loop). Otherwise we
    // emit the default LLM-driven loop over prompt variants + test cases.
    if !provides("try_variant") {
        let _ = writeln!(out, "// ── Hill-climb target — driven by goal_run ───────────────");
        // A prose `@[contained(...)]` effect surface is stamped on the loop so the
        // compiler ENFORCES it (E1001/E1004): `try_variant` and everything it calls
        // (build_prompt, score_output, ai_complete) must stay within the declared
        // capabilities, transitively. The prose surface becomes a hard boundary.
        if let Some(contained) = goal.contained_attr() {
            let _ = writeln!(out, "// effect surface declared in prose — compiler-enforced:");
            let _ = writeln!(out, "{contained}");
        }
        let _ = writeln!(out, "@[adaptive]");
        let _ = writeln!(out, "fn try_variant(variant_id: i64) -> i64 {{");
        let _ = writeln!(out, "    let prompt = build_prompt(variant_id)");
        let _ = writeln!(out, "    let total = 0");
        let _ = writeln!(out, "    let i = 0");
        let _ = writeln!(out, "    while i < 2 {{");
        let _ = writeln!(out, "        let inp = test_input(i)");
        let _ = writeln!(out, "        let full = \"{{prompt}}{{inp}}\"");
        let _ = writeln!(out, "        match ai_complete(full) {{");
        let _ = writeln!(out, "            Ok(reply) => {{ total = total + score_output(inp, reply) }}");
        let _ = writeln!(out, "            Err(_) => {{}}");
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "        i = i + 1");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "    total / 2");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    } else if goal.contained_attr().is_some() {
        // The author supplied their own try_variant, so we can't stamp the prose
        // effect surface onto it — flag it loudly rather than silently dropping
        // the declared boundary (the author must add @[contained(...)] themselves).
        let _ = writeln!(
            out,
            "// NOTE: the prose declares an effect surface (@[contained]) but you supplied your own"
        );
        let _ = writeln!(
            out,
            "// `try_variant` — add that @[contained(...)] attribute to it so the compiler enforces it."
        );
        let _ = writeln!(out);
    }

    // ── Verify gate ──────────────────────────────────────────────
    // The prose predicate may be richer than Axon's v0 verify form
    // (`<metric> OP <number>`), so preserve it verbatim as a comment and emit
    // a valid `score`-threshold gate the skeleton can actually compile and run.
    let predicate = goal.verify_predicate()?;
    let target = extract_target_from_predicate(&predicate).unwrap_or(70);
    // Evaluation budget from the prose Budget section bounds goal_run's search.
    let budget = goal.budget_evals().unwrap_or(20);
    // The author may supply their own `assert_deployable` (e.g. a confidence-
    // returning gate that the runtime `@[verify]` check actually enforces).
    // Otherwise emit a pass-through gate carrying the prose predicate's threshold.
    if !provides("assert_deployable") {
        let _ = writeln!(out, "// ── Verify gate (derived from prose) ──────────────────────");
        let _ = writeln!(out, "// prose predicate: {predicate}");
        let _ = writeln!(out, "@[verify(score >= {target})]");
        let _ = writeln!(out, "fn assert_deployable(score: i64) -> i64 {{");
        let _ = writeln!(out, "    score");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // ── Main ─────────────────────────────────────────────────────
    let _ = writeln!(out, "// ── Main loop ────────────────────────────────────────────");
    let _ = writeln!(out, "fn main() -> i64 {{");
    let _ = writeln!(out, "    println(\"goal: {} — searching variants...\")", goal.title);
    // goal_run drives the @[adaptive] try_variant (hill-climbing variant_id).
    // Its target is an f64; the result is converted back to i64 for the gate.
    // If the author supplied a `feasible(variant_id) -> bool` predicate (the prose
    // Constraints section, encoded), the search is CONSTRAINED: goal_run_constrained
    // only accepts feasible candidates — a hard gate, so the prose constraint is
    // actually enforced during the search, not just documented.
    if provides("feasible") {
        let _ = writeln!(out, "    // constrained by the author's `feasible` predicate (prose Constraints)");
        let _ = writeln!(out, "    let result = goal_run_constrained(\"try_variant\", \"feasible\", {target}.0, {budget})");
    } else {
        let _ = writeln!(out, "    let result = goal_run(\"try_variant\", {target}.0, {budget})");
    }
    let _ = writeln!(out, "    let best = f64_to_i64(result)");
    let _ = writeln!(out, "    println(\"best score: {{to_str(best)}} (target {target})\")");
    let _ = writeln!(out, "    let _ = assert_deployable(best)");
    // If the author supplied a `redteam_check() -> bool`, the goal deploys only
    // when the adversarial check ALSO passes — verify gate AND redteam.
    if provides("redteam_check") {
        let _ = writeln!(out, "    if redteam_check() {{");
        let _ = writeln!(out, "        println(\"deploy gate: passed (verify + redteam)\")");
        let _ = writeln!(out, "        0");
        let _ = writeln!(out, "    }} else {{");
        let _ = writeln!(out, "        println(\"REDTEAM FAILED: blocking deploy\")");
        // BUG_HUNT #34 (surface): a redteam rejection is a *policy* rejection,
        // the same class as a failed `@[verify]` deploy-gate — so it exits 3
        // (VERIFY_FAILED_EXIT_CODE), NOT 1. This unifies every goal deploy-gate
        // rejection (verify, redteam, future gates) under one exit class so a
        // supervisor can branch on "policy blocked deploy" (3) vs "the program
        // crashed" (101) vs clean (0). Pre-#34 this returned 1, conflated with
        // an ordinary failure.
        let _ = writeln!(out, "        3");
        let _ = writeln!(out, "    }}");
    } else {
        let _ = writeln!(out, "    println(\"deploy gate: passed\")");
        let _ = writeln!(out, "    0");
    }
    let _ = writeln!(out, "}}");

    Ok(out)
}

/// Try to pull a numeric threshold out of a verify predicate.
/// E.g., "score >= 70" → 70; "confidence >= 0.9" → can't (float, fallback).
fn extract_target_from_predicate(p: &str) -> Option<i64> {
    for tok in p.split_whitespace() {
        if let Ok(n) = tok.parse::<i64>() {
            return Some(n);
        }
    }
    None
}

/// Split [`PRELUDE_SRC`] into `(fn_name, full_definition_text)` pairs — one per
/// top-level `fn` (those starting at column 0). Header/inter-fn comment lines
/// are dropped; only the definitions are returned.
fn prelude_fns() -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = Vec::new();
    let mut name: Option<String> = None;
    let mut body = String::new();
    for line in PRELUDE_SRC.lines() {
        if let Some(rest) = line.strip_prefix("fn ") {
            if let Some(n) = name.take() {
                out.push((n, body.trim_end().to_string()));
                body.clear();
            }
            name = Some(rest.split('(').next().unwrap_or("").trim().to_string());
        }
        if name.is_some() {
            body.push_str(line);
            body.push('\n');
        }
    }
    if let Some(n) = name {
        out.push((n, body.trim_end().to_string()));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::GoalFile;

    const SAMPLE: &str = r#"# Goal: Test sample

## Intent

Do a thing.

## Inputs

- `text: str` — input.

## Outputs

- `summary: str` — output.

## Score (higher is better)

Some scoring.

## Constraints

- A constraint.

## Budget

- 100 calls.

## Verify

```axon
@[verify(score >= 70)]
```

## Redteam

- Some adversarial test.

## Effect surface

- Just LLM calls.

## Provenance

- JSONL log.
"#;

    #[test]
    fn emits_compileable_skeleton() {
        let g = GoalFile::parse(SAMPLE).unwrap();
        let ax = emit(&g).unwrap();
        // Header.
        assert!(ax.starts_with("// Goal: Test sample"));
        // Verify gate carried through (score-threshold form derived from prose).
        assert!(ax.contains("@[verify(score >= 70)]"));
        // Prose predicate preserved as a comment.
        assert!(ax.contains("// prose predicate: score >= 70"));
        // Function signature uses input type from prose.
        assert!(ax.contains("fn test_input(i: i64) -> str"));
        // Goal_run drives the adaptive try_variant with an f64 target and the
        // prose Budget ("100 calls") as max_evals.
        assert!(ax.contains("goal_run(\"try_variant\", 70.0, 100)"));
        // Adaptive annotation present.
        assert!(ax.contains("@[adaptive]"));
        // Build_prompt present.
        assert!(ax.contains("fn build_prompt(variant_id: i64) -> str"));
        // With no author code blocks, the score scaffold is emitted.
        assert!(ax.contains("// TODO: implement the score formula"));
    }

    #[test]
    fn redteam_rejection_exits_with_the_policy_code_3() {
        // BUG_HUNT #34 (surface): a redteam-check failure is a POLICY rejection,
        // the same class as a failed @[verify] deploy-gate, so the generated
        // `main` must return 3 (VERIFY_FAILED_EXIT_CODE) on the fail branch —
        // NOT 1 (which conflated it with an ordinary failure). The deploy/pass
        // branch still returns 0.
        let md = format!(
            "{SAMPLE}\n## Implementation\n\n```axon\n\
             fn redteam_check() -> bool {{ false }}\n```\n"
        );
        let g = GoalFile::parse(&md).unwrap();
        let ax = emit(&g).unwrap();
        assert!(ax.contains("if redteam_check() {"), "redteam gate must be wired: {ax}");
        // The fail branch returns the policy code 3, not 1.
        let fail_idx = ax.find("REDTEAM FAILED").expect("fail branch present");
        let after = &ax[fail_idx..];
        assert!(
            after.contains("\n        3\n"),
            "redteam fail branch must return 3 (policy code), not 1: {after}"
        );
        assert!(
            !after[..after.find("}}").unwrap_or(after.len()).min(80)].contains('1'),
            "redteam fail branch must not return 1"
        );
    }

    #[test]
    fn feasible_predicate_wires_constrained_search() {
        // A `feasible(variant_id) -> bool` predicate supplied in a prose ```axon
        // block (the Constraints section, encoded) makes the generated search
        // CONSTRAINED: `main` drives goal_run_constrained, not goal_run, so the
        // prose constraint is ENFORCED during the search rather than merely
        // documented. Same author-provides-fn → scaffold-wires-it pattern as
        // redteam_check, but a hard per-candidate feasibility gate.
        let md = format!(
            "{SAMPLE}\n## Implementation\n\n```axon\n\
             fn feasible(variant_id: i64) -> bool {{ variant_id >= 0 }}\n```\n"
        );
        let g = GoalFile::parse(&md).unwrap();
        let ax = emit(&g).unwrap();
        assert!(ax.contains("fn feasible(variant_id: i64) -> bool"), "feasible lifted: {ax}");
        assert!(
            ax.contains("goal_run_constrained(\"try_variant\", \"feasible\", 70.0, 100)"),
            "constrained search must be wired when feasible is provided: {ax}"
        );
        assert!(
            !ax.contains("goal_run(\"try_variant\""),
            "must NOT also emit the unconstrained goal_run: {ax}"
        );
    }

    #[test]
    fn prose_effect_surface_is_compiler_enforced_via_contained() {
        // A `@[contained(...)]` declaration in the Effect surface section is
        // stamped onto the generated try_variant, so the prose-declared
        // capabilities are ENFORCED (E1001/E1004 at `axon check`), not merely
        // documented — the value wedge applied to a prose goal. It must precede
        // the @[adaptive] loop and must NOT also be lifted as orphan author code.
        let md = SAMPLE.replace(
            "## Effect surface\n\n- Just LLM calls.",
            "## Effect surface\n\n@[contained(net: [\"api.anthropic.com\"], exec: none)]",
        );
        let g = GoalFile::parse(&md).unwrap();
        assert_eq!(
            g.contained_attr().as_deref(),
            Some("@[contained(net: [\"api.anthropic.com\"], exec: none)]"),
            "contained_attr must extract the bracket-balanced declaration"
        );
        let ax = emit(&g).unwrap();
        let ci = ax.find("@[contained").expect("contained stamped on the loop");
        let ai = ax.find("@[adaptive]").expect("adaptive try_variant present");
        assert!(ci < ai, "@[contained] must precede the @[adaptive] loop: {ax}");
        assert_eq!(
            ax.matches("@[contained").count(),
            1,
            "exactly one @[contained] (not also lifted as orphan author code): {ax}"
        );
    }

    #[test]
    fn bundles_only_referenced_prelude_helpers() {
        // Author score_output references normalize_score → it's auto-included;
        // unreferenced prelude helpers (weighted2) are not.
        let md = format!(
            "{SAMPLE}\n## Implementation\n\n```axon\n\
             fn score_output(text: str, summary: str) -> i64 {{ normalize_score(len(summary), 100) }}\n```\n"
        );
        let g = GoalFile::parse(&md).unwrap();
        let ax = emit(&g).unwrap();
        assert!(ax.contains("// ── Prelude"), "prelude header missing");
        assert!(ax.contains("fn normalize_score("), "referenced helper not bundled");
        assert!(!ax.contains("fn weighted2("), "unreferenced helper should not be bundled");
    }

    #[test]
    fn lifts_author_bodies_and_drops_scaffold() {
        // SAMPLE plus an Implementation section that supplies score_output.
        let md = format!(
            "{SAMPLE}\n## Implementation\n\n```axon\n\
             fn score_output(text: str, summary: str) -> i64 {{ len(summary) }}\n```\n"
        );
        let g = GoalFile::parse(&md).unwrap();
        let ax = emit(&g).unwrap();
        // Author body lifted verbatim.
        assert!(ax.contains("// ── Author-supplied"));
        assert!(ax.contains("fn score_output(text: str, summary: str) -> i64 { len(summary) }"));
        // The provided helper's scaffold is dropped...
        assert!(!ax.contains("// TODO: implement the score formula"));
        // ...but unprovided helpers still get scaffolds.
        assert!(ax.contains("fn build_prompt(variant_id: i64) -> str"));
        assert!(ax.contains("fn test_input(i: i64) -> str"));
    }
}
