//! The protected guest image is built in an environment the build CONSTRUCTS
//! (scripts/guest_build_env.py), not one it filters by a list of names
//! (C9 round 4, FIELD-ORIGIN / PSV-2 / EQUIVALENCE; two reviewers built
//! through an ancestor `.cargo/config.toml`, a dotted `build.rustc-wrapper`,
//! RUSTC/RUSTFLAGS and a reused target dir, and the old guard passed each).
//!
//! C9 round 4b (FIELD-ORIGIN, amendment 63): the build runs on a PRIVATE copy
//! of the tracked tree under a directory only root or the builder can write,
//! with cargo's effective config held to begin's before and after EVERY
//! invocation; only the table's exact invocations run; and the kernel and the
//! rootfs are made in the same discipline.
//!
//! These run the PRODUCTION route: `scripts/build-guest-image.sh
//! --build-env-only`, the same `gcargo_begin` every guest build starts with,
//! and the `guest_build_env.py cargo` / `rootfs` / `kernel` steps the image
//! build calls, from a scratch checkout of this tree's files.

#[path = "../../axon-core/tests/script_spawn/mod.rs"]
mod script_spawn;
use script_spawn::{repo_root, Bins};
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};

/// The files the controlled-build step reads, copied from THIS tree.
const COPIED: [&str; 4] = [
    "scripts/build-guest-image.sh",
    "scripts/guest_build_env.py",
    "rust-toolchain.toml",
    ".cargo/config.toml",
];
const CRT: &str = "-C target-feature=+crt-static";
/// The protected `axon-guest-init` invocation (guest_build_env.py
/// PROTECTED_BUILDS), exactly: the checkout's one crate has that name.
const GUEST_INIT: [&str; 8] = [
    "build",
    "--locked",
    "-p",
    "axon-guest-init",
    "--target",
    "x86_64-unknown-linux-musl",
    "--release",
    "--quiet",
];

fn write(p: &Path, s: &str) {
    std::fs::create_dir_all(p.parent().unwrap()).unwrap();
    std::fs::write(p, s).unwrap();
}

fn chmod(p: &Path, mode: u32) {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(p, std::fs::Permissions::from_mode(mode)).unwrap();
}

fn chmod_x(p: &Path) {
    chmod(p, 0o755);
}

fn sha(p: &Path) -> String {
    format!("{:x}", Sha256::digest(std::fs::read(p).unwrap()))
}

fn git(r: &Path, args: &[&str]) {
    let st = Command::new("/usr/bin/git")
        .arg("-C")
        .arg(r)
        .args(["-c", "user.name=t", "-c", "user.email=t@example"])
        .args(args)
        .stdout(Stdio::null())
        .status()
        .unwrap();
    assert!(st.success(), "git {args:?}");
}

/// A git checkout at `<parent>/repo` holding the build's files and a one-crate
/// workspace whose crate is named `axon-guest-init` (no dependencies, so a
/// fresh CARGO_HOME builds it offline), plus a rootfs profile whose busybox
/// is a fixture at `<parent>/busybox`. The build copies its TRACKED files.
fn checkout(parent: &Path) -> PathBuf {
    let r = parent.join("repo");
    for f in COPIED {
        write(
            &r.join(f),
            &std::fs::read_to_string(repo_root().join(f)).unwrap(),
        );
    }
    write(
        &r.join("Cargo.toml"),
        "[workspace]\nmembers = [\"guest\"]\nresolver = \"2\"\n",
    );
    write(
        &r.join("guest/Cargo.toml"),
        "[package]\nname = \"axon-guest-init\"\nversion = \"0.0.0\"\nedition = \"2021\"\n",
    );
    write(&r.join("guest/src/main.rs"), "fn main() {}\n");
    write(
        &r.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual \
         editing.\nversion = 4\n\n[[package]]\nname = \"axon-guest-init\"\nversion = \"0.0.0\"\n",
    );
    let bb = parent.join("busybox");
    write(&bb, "#!/bin/sh\necho sh\necho ls\necho busybox\n");
    chmod_x(&bb);
    write(
        &r.join("profiles/linux-microvm/kernel.pin"),
        &format!(
            "BUSYBOX_SRC={}\nBUSYBOX_SHA256={}\n",
            bb.display(),
            sha(&bb)
        ),
    );
    write(
        &r.join("profiles/linux-microvm/guest-init.sh"),
        "#!/bin/sh\necho init\n",
    );
    git(&r, &["init", "-q", "-b", "main"]);
    git(&r, &["add", "-A"]);
    r
}

/// `build-guest-image.sh --build-env-only <out>`: the controlled environment
/// alone, recorded in `<out>/build-env.json`.
fn build_env_only(repo: &Path, out: &Path, env: &[(&str, String)]) -> Output {
    let mut c = script_spawn::script(
        "bash",
        repo.join("scripts/build-guest-image.sh"),
        Bins::BuildsItsOwn,
    );
    c.arg("--build-env-only")
        .arg(out)
        .current_dir(repo)
        .env("AXON_GUEST_BUILD_PARENT", test_parent());
    for (k, v) in env {
        c.env(k, v);
    }
    c.output().unwrap()
}

/// Where a real controlled build keeps its private directories and proof keys.
fn real_parent() -> PathBuf {
    PathBuf::from(std::env::var("HOME").unwrap())
        .join(".cache")
        .join("axon-guest-build")
}

/// The build parent every build these tests start uses: a directory made for
/// THIS test process under the builder's home (only root's or the builder's
/// ancestors), removed at exit. Never `~/.cache/axon-guest-build`: a test run
/// must not leave keys or build directories in the real builder-private place.
fn test_parent() -> &'static Path {
    use std::os::unix::fs::PermissionsExt;
    static P: std::sync::OnceLock<PathBuf> = std::sync::OnceLock::new();
    static CLEAN: std::sync::OnceLock<std::ffi::CString> = std::sync::OnceLock::new();
    P.get_or_init(|| {
        let d = PathBuf::from(std::env::var("HOME").unwrap())
            .join(".cache")
            .join(format!("axon-gbe-test-{}", std::process::id()));
        std::fs::create_dir_all(&d).unwrap();
        std::fs::set_permissions(&d, std::fs::Permissions::from_mode(0o700)).unwrap();
        assert!(
            !d.starts_with(real_parent()),
            "ATTACK: a test would build under the real builder-private parent"
        );
        extern "C" fn clean() {
            if let Some(p) = CLEAN.get() {
                let _ = std::fs::remove_dir_all(p.to_str().unwrap());
            }
        }
        CLEAN
            .set(std::ffi::CString::new(d.to_str().unwrap()).unwrap())
            .unwrap();
        unsafe { libc::atexit(clean) };
        d.join("parent")
    })
}

/// `guest_build_env.py ...` from the checkout.
fn gbe(repo: &Path) -> Command {
    let mut c = script_spawn::script(
        "python3",
        repo.join("scripts/guest_build_env.py"),
        Bins::BuildsItsOwn,
    );
    c.current_dir(repo)
        .env("AXON_GUEST_BUILD_PARENT", test_parent());
    c
}

/// `guest_build_env.py cargo REC [--rustflags F] -- ARGS`: one controlled step.
fn gcargo(repo: &Path, rec: &Path, rustflags: Option<&str>, args: &[&str]) -> Output {
    let mut c = gbe(repo);
    c.arg("cargo").arg(rec);
    if let Some(f) = rustflags {
        c.args(["--rustflags", f]);
    }
    c.arg("--").args(args);
    c.output().unwrap()
}

fn record(out: &Path) -> Value {
    let rec: Value =
        serde_json::from_slice(&std::fs::read(out.join("build-env.json")).unwrap()).unwrap();
    let parent = PathBuf::from(rec["build_parent"].as_str().unwrap_or("/"));
    assert!(
        !parent.starts_with(real_parent()),
        "ATTACK: a test built under the real builder-private parent {}",
        parent.display()
    );
    rec
}

/// The private build directory (the parent of the fresh target dir).
fn base_of(rec: &Value) -> PathBuf {
    Path::new(rec["target_dir"].as_str().unwrap())
        .parent()
        .unwrap()
        .to_path_buf()
}

/// Remove the private build directory a successful begin created.
fn discard(rec: &Value) {
    if rec["target_dir"].as_str().is_some() {
        let base = base_of(rec);
        if base
            .file_name()
            .is_some_and(|n| n.to_string_lossy().starts_with("axon-guest-build-"))
        {
            let _ = std::fs::remove_dir_all(base);
        }
    }
}

fn text(o: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&o.stdout),
        String::from_utf8_lossy(&o.stderr)
    )
}

/// A scratch directory under the builder's home: its ancestors are only
/// root's or the builder's, so it may hold a build parent.
fn private_scratch() -> tempfile::TempDir {
    let cache = PathBuf::from(std::env::var("HOME").unwrap()).join(".cache");
    std::fs::create_dir_all(&cache).unwrap();
    tempfile::tempdir_in(cache).unwrap()
}

/// A rustc wrapper that leaves `marker` behind and runs the compiler.
fn wrapper(dir: &Path, marker: &Path) -> PathBuf {
    let w = dir.join("wrapper");
    write(
        &w,
        &format!("#!/bin/sh\n: > '{}'\nexec \"$@\"\n", marker.display()),
    );
    chmod_x(&w);
    w
}

/// A begun controlled build of a fresh checkout under `d`: (repo, record path, record).
fn begun(d: &Path) -> (PathBuf, PathBuf, Value) {
    let r = checkout(d);
    let out = d.join("out");
    let o = build_env_only(&r, &out, &[]);
    assert!(o.status.success(), "setup: begin: {}", text(&o));
    let rec = record(&out);
    (r, out.join("build-env.json"), rec)
}

/// cargo's EFFECTIVE configuration, as it resolves it from the build's
/// directory, may hold nothing the guest build would use -- from an ancestor
/// directory's config, in the dotted-key spelling, or committed to the tree's
/// own config. Control: the tree's own config (wasm-only rustflags) passes.
#[test]
fn a_cargo_config_setting_the_guest_build_would_use_is_refused() {
    let cases: [(&str, &str, bool); 5] = [
        (
            "an ancestor .cargo/config.toml naming a rustc wrapper",
            "[build]\nrustc-wrapper = \"/usr/bin/sccache\"\n",
            false,
        ),
        (
            "an ancestor config in the dotted-key spelling",
            "build.rustc-wrapper = \"/usr/bin/sccache\"\n",
            false,
        ),
        (
            "an ancestor config naming a linker for the guest's target",
            "[target.x86_64-unknown-linux-musl]\nlinker = \"/tmp/evil-cc\"\n",
            false,
        ),
        (
            "an ancestor config adding rustflags",
            "[build]\nrustflags = [\"--cfg\", \"evil\"]\n",
            false,
        ),
        (
            "the tree's own config naming a rustc",
            "build.rustc = \"/tmp/evil-rustc\"\n",
            true,
        ),
    ];
    for (attack, cfg, own) in cases {
        let d = tempfile::tempdir().unwrap();
        let r = checkout(d.path());
        // The build parent's ancestors are where cargo, running in the private
        // copy, looks: a config there (written by root or the builder, the
        // only uids that can) is in its effective configuration.
        let scratch = private_scratch();
        let parent = scratch.path().join("parent");
        if own {
            let p = r.join(".cargo/config.toml");
            // At the top, so the dotted key is not inside the file's tables.
            let s = std::fs::read_to_string(&p).unwrap();
            write(&p, &format!("{cfg}{s}"));
            git(&r, &["add", "-A"]);
        } else {
            write(&scratch.path().join(".cargo/config.toml"), cfg);
        }
        let out = d.path().join("out");
        let o = build_env_only(
            &r,
            &out,
            &[("AXON_GUEST_BUILD_PARENT", parent.display().to_string())],
        );
        if o.status.success() {
            discard(&record(&out));
        }
        assert!(
            !o.status.success(),
            "ATTACK: the guest build ran under a cargo config setting it would use ({attack}):\n{}",
            text(&o)
        );
        assert!(
            text(&o).contains("effective configuration"),
            "{attack}: {}",
            text(&o)
        );
    }
    // Control: the tree's own config alone.
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let out = d.path().join("out");
    let o = build_env_only(&r, &out, &[]);
    assert!(
        o.status.success(),
        "control: the tree's own config builds: {}",
        text(&o)
    );
    let rec = record(&out);
    discard(&rec);
    assert_eq!(rec["effective_config"]["foreign"], serde_json::json!([]));
}

/// Cargo runs in the environment the build constructs, never the caller's:
/// a RUSTC_WRAPPER (and friends) exported by whoever launched the build does
/// not reach the compile. Control: the step builds, into the fresh target dir.
#[test]
fn a_callers_compiler_wrapper_does_not_reach_the_guest_builds_cargo() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, _) = begun(d.path());
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker);
    let mut c = gbe(&r);
    c.arg("cargo")
        .arg(&rec_path)
        .args(["--rustflags", CRT, "--"])
        .args(GUEST_INIT);
    for v in [
        "RUSTC_WRAPPER",
        "RUSTC_WORKSPACE_WRAPPER",
        "CARGO_BUILD_RUSTC_WRAPPER",
    ] {
        c.env(v, &w);
    }
    c.env("RUSTC", "/bin/false")
        .env("RUSTFLAGS", "--cfg evil")
        .env("CARGO_BUILD_RUSTC", "/bin/false");
    let b = c.output().unwrap();
    let rec: Value = serde_json::from_slice(&std::fs::read(&rec_path).unwrap()).unwrap();
    let built = gpath(&r, &rec_path, "axon-guest-init");
    let (ran, exists) = (marker.exists(), built.exists());
    discard(&rec);
    assert!(
        !ran,
        "ATTACK: a caller's RUSTC_WRAPPER reached the guest build's cargo:\n{}",
        text(&b)
    );
    assert!(
        b.status.success() && exists,
        "control: the controlled step builds, into the fresh target dir:\n{}",
        text(&b)
    );
}

/// The toolchain is the one rust-toolchain.toml pins, as rustup resolves it
/// under a CLEARED environment: a caller's RUSTUP_HOME holding a toolchain of
/// the same name does not choose the compiler. Control: the recorded rustc
/// is the invoking user's real toolchain.
#[test]
fn a_callers_rustup_home_does_not_choose_the_guest_toolchain() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let chan = std::fs::read_to_string(r.join("rust-toolchain.toml"))
        .unwrap()
        .lines()
        .find_map(|l| {
            l.trim().strip_prefix("channel").map(|v| {
                v.split('=')
                    .nth(1)
                    .unwrap()
                    .trim()
                    .trim_matches('"')
                    .to_string()
            })
        })
        .unwrap();
    let fake_home = d.path().join("fake-rustup");
    let bin = fake_home.join(format!("toolchains/{chan}-x86_64-unknown-linux-gnu/bin"));
    for tool in ["cargo", "rustc"] {
        write(
            &bin.join(tool),
            "#!/bin/sh\ncase \"$*\" in *config*) exit 0;; esac\necho \"fake 1.0 (planted)\"\n",
        );
        chmod_x(&bin.join(tool));
    }
    let out = d.path().join("out");
    let o = build_env_only(
        &r,
        &out,
        &[
            ("RUSTUP_HOME", fake_home.display().to_string()),
            ("RUSTUP_TOOLCHAIN", chan.clone()),
        ],
    );
    let rec = if o.status.success() {
        record(&out)
    } else {
        Value::Null
    };
    discard(&rec);
    let rustc = rec["toolchain"]["rustc"].as_str().unwrap_or("");
    assert!(
        !rustc.starts_with(fake_home.to_str().unwrap()),
        "ATTACK: a caller's RUSTUP_HOME chose the guest build's compiler ({rustc})"
    );
    assert!(
        o.status.success() && Path::new(rustc).is_file(),
        "control: the pinned toolchain resolves: {}",
        text(&o)
    );
}

/// Round 4b, finding 1: the build parent is refused unless only root or the
/// builder can write every ancestor -- a directory any uid can write (a
/// sticky /var/tmp included) is one where another uid plants a config cargo
/// reads. Control: the default parent, under the builder's home, begins
/// (every other test here).
#[test]
fn a_guest_build_under_a_directory_another_uid_can_write_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let scratch = private_scratch();
    let open = scratch.path().join("open");
    std::fs::create_dir_all(&open).unwrap();
    chmod(&open, 0o1777);
    let out = d.path().join("out");
    let o = build_env_only(
        &r,
        &out,
        &[(
            "AXON_GUEST_BUILD_PARENT",
            open.join("parent").display().to_string(),
        )],
    );
    if o.status.success() {
        discard(&record(&out));
    }
    assert!(
        !o.status.success(),
        "ATTACK: the guest build began under a directory any uid can write:\n{}",
        text(&o)
    );
    assert!(
        text(&o).contains("not private to the builder"),
        "{}",
        text(&o)
    );
}

/// Round 4b, finding 1, as the reviewer executed it: a `.cargo/config.toml`
/// naming a rustc wrapper, written into an ancestor of the CLONE after
/// `begin`, used to wrap every rustc of the next build. Cargo now runs in the
/// build's private copy, so the clone's ancestors are not where it looks.
/// Control: the step builds.
#[test]
fn an_ancestor_config_written_after_begin_does_not_reach_the_guest_build() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, rec) = begun(d.path());
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker);
    // An ancestor of the clone (the checkout), written AFTER begin.
    write(
        &d.path().join(".cargo/config.toml"),
        &format!("build.rustc-wrapper = \"{}\"\n", w.display()),
    );
    let b = gcargo(&r, &rec_path, Some(CRT), &GUEST_INIT);
    discard(&rec);
    assert!(
        !marker.exists(),
        "ATTACK: an ancestor config written after begin wrapped the guest build's rustc:\n{}",
        text(&b)
    );
    assert!(b.status.success(), "control: the step builds: {}", text(&b));
}

/// Round 4b, finding 1: cargo's effective config is held to begin's BEFORE
/// every invocation. A config placed (by the only uids that can) beside the
/// private copy after begin is refused before cargo starts, so its wrapper
/// never runs.
#[test]
fn a_cargo_config_planted_beside_the_private_copy_after_begin_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, rec) = begun(d.path());
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker);
    write(
        &base_of(&rec).join(".cargo/config.toml"),
        &format!("build.rustc-wrapper = \"{}\"\n", w.display()),
    );
    let b = gcargo(&r, &rec_path, Some(CRT), &GUEST_INIT);
    discard(&rec);
    assert!(
        !marker.exists(),
        "ATTACK: a cargo config planted after begin reached the guest build's compiler:\n{}",
        text(&b)
    );
    assert!(
        !b.status.success() && text(&b).contains("changed since begin"),
        "{}",
        text(&b)
    );
}

/// Round 4b, finding 1: and AFTER every invocation. A config that appears
/// while a step runs (here a build script writes one beside the private copy)
/// fails that step, and its record entry carries the differing check.
#[test]
fn a_cargo_config_written_during_a_guest_build_step_fails_that_step() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    write(
        &r.join("guest/build.rs"),
        "use std::path::PathBuf;\nfn main() {\n    let mut p = \
         PathBuf::from(std::env::var(\"OUT_DIR\").unwrap());\n    while \
         !p.join(\"cargo-home\").is_dir() {\n        if !p.pop() {\n            return;\n        \
         }\n    }\n    std::fs::create_dir_all(p.join(\".cargo\")).unwrap();\n    \
         std::fs::write(p.join(\".cargo/config.toml\"), \"[build]\\njobs = 1\\n\").unwrap();\n}\n",
    );
    git(&r, &["add", "-A"]);
    let out = d.path().join("out");
    let o = build_env_only(&r, &out, &[]);
    assert!(o.status.success(), "setup: {}", text(&o));
    let rec = record(&out);
    let b = gcargo(&r, &out.join("build-env.json"), Some(CRT), &GUEST_INIT);
    let written = base_of(&rec).join(".cargo/config.toml").exists();
    discard(&rec);
    assert!(written, "setup: the build script wrote the config");
    assert!(
        !b.status.success(),
        "ATTACK: a cargo config written during a guest build step left that step succeeded:\n{}",
        text(&b)
    );
    assert!(text(&b).contains("changed DURING"), "{}", text(&b));
}

/// Round 4b, finding 2: the step runs only an invocation in the table,
/// exactly. Extra RUSTFLAGS (a linker) or an extra `--config` naming a
/// wrapper is refused before cargo starts. Control: the exact invocation
/// builds (a_callers_compiler_wrapper_does_not_reach_the_guest_builds_cargo).
#[test]
fn a_guest_cargo_step_with_extra_flags_or_args_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, rec) = begun(d.path());
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker);
    let wrap_cfg = format!("build.rustc-wrapper=\"{}\"", w.display());
    let mut with_config: Vec<&str> = GUEST_INIT.to_vec();
    with_config.splice(1..1, ["--config", wrap_cfg.as_str()]);
    let linker = format!("{CRT} -C linker={}", w.display());
    let cases: [(&str, &str, Vec<&str>); 3] = [
        ("a --config naming a rustc wrapper", CRT, with_config),
        (
            "extra RUSTFLAGS naming a linker",
            linker.as_str(),
            GUEST_INIT.to_vec(),
        ),
        (
            "a -Z flag",
            CRT,
            [GUEST_INIT.as_slice(), &["-Z", "unstable-options"]].concat(),
        ),
    ];
    for (attack, flags, args) in cases {
        let b = gcargo(&r, &rec_path, Some(flags), &args);
        assert!(
            !marker.exists() && !b.status.success(),
            "ATTACK: a guest cargo step outside its table ran ({attack}):\n{}",
            text(&b)
        );
        assert!(
            text(&b).contains("not a controlled guest build invocation"),
            "{attack}: {}",
            text(&b)
        );
    }
    discard(&rec);
}

/// Where the controlled build puts a musl release binary, as its own `path`
/// step answers (the production route, never a joined guess).
fn gpath(r: &Path, rec_path: &Path, name: &str) -> PathBuf {
    let o = gbe(r)
        .arg("path")
        .arg(rec_path)
        .args(["x86_64-unknown-linux-musl", "release", name])
        .output()
        .unwrap();
    assert!(o.status.success(), "setup: path: {}", text(&o));
    PathBuf::from(String::from_utf8_lossy(&o.stdout).trim())
}

/// Fake artifacts at the paths the controlled build would put them, `finish`ed
/// into the record (the rootfs step reads the record, not cargo).
fn finished(r: &Path, rec_path: &Path) {
    let mut pairs = vec![];
    for name in ["axon", "axon-guest-init", "axon-psv-runner"] {
        let p = gpath(r, rec_path, name);
        write(&p, &format!("#!/bin/sh\necho {name}\n"));
        pairs.push(format!("{name}={}", p.display()));
    }
    let o = gbe(r)
        .arg("finish")
        .arg(rec_path)
        .args(&pairs)
        .output()
        .unwrap();
    assert!(o.status.success(), "setup: finish: {}", text(&o));
}

/// Round 4b, finding 3: the rootfs is assembled only from the bytes the
/// controlled build recorded. A binary replaced after the build is refused.
/// Control: the recorded bytes assemble, and the record names the output.
#[test]
fn a_rootfs_from_a_binary_the_controlled_build_did_not_produce_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, _) = begun(d.path());
    finished(&r, &rec_path);
    let runner = gpath(&r, &rec_path, "axon-psv-runner");
    let honest = std::fs::read(&runner).unwrap();
    std::fs::write(&runner, b"#!/bin/sh\necho forged runner\n").unwrap();
    let sq = d.path().join("rootfs.sqfs");
    let o = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .output()
        .unwrap();
    std::fs::write(&runner, honest).unwrap();
    assert!(
        !o.status.success(),
        "ATTACK: the rootfs was assembled from a binary the controlled build did not produce:\n{}",
        text(&o)
    );
    assert!(text(&o).contains("is not the bytes"), "{}", text(&o));
    let c = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .output()
        .unwrap();
    let after: Value = serde_json::from_slice(&std::fs::read(&rec_path).unwrap()).unwrap();
    discard(&after);
    assert!(
        c.status.success(),
        "control: the rootfs assembles: {}",
        text(&c)
    );
    assert_eq!(
        after["rootfs"]["sha256"],
        sha(&sq),
        "control: output recorded"
    );
    assert_eq!(after["rootfs"]["tool"]["path"], "/usr/bin/mksquashfs");
}

/// Round 4b, finding 3: the rootfs is made by /usr/bin/mksquashfs under a
/// constructed environment, never one on the caller's PATH; the busybox
/// installed is the pinned one (its COPY verified). Control: the step
/// succeeds with the planted PATH.
#[test]
fn a_callers_mksquashfs_or_busybox_does_not_make_the_rootfs() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, rec) = begun(d.path());
    finished(&r, &rec_path);
    let evil = d.path().join("evil-bin");
    let marker = d.path().join("evil-mksquashfs-ran");
    // Writes the output it is asked for, so nothing else in the step refuses.
    write(
        &evil.join("mksquashfs"),
        &format!(
            "#!/bin/sh\n: > '{}'\nprintf forged > \"$2\"\n",
            marker.display()
        ),
    );
    chmod_x(&evil.join("mksquashfs"));
    let sq = d.path().join("rootfs.sqfs");
    let path = format!("{}:{}", evil.display(), std::env::var("PATH").unwrap());
    let o = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .env("PATH", &path)
        .output()
        .unwrap();
    assert!(
        !marker.exists(),
        "ATTACK: a mksquashfs on the caller's PATH made the rootfs:\n{}",
        text(&o)
    );
    assert!(
        o.status.success(),
        "control: the rootfs assembles: {}",
        text(&o)
    );
    // The pinned busybox's bytes changed after the pin: refused.
    let bb = d.path().join("busybox");
    std::fs::write(&bb, "#!/bin/sh\necho sh\necho forged\n").unwrap();
    let o = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .output()
        .unwrap();
    discard(&rec);
    assert!(
        !o.status.success(),
        "ATTACK: the rootfs installed a busybox that is not the pinned one:\n{}",
        text(&o)
    );
    assert!(text(&o).contains("busybox sha256 mismatch"), "{}", text(&o));
}

/// A kernel "source tarball" whose Makefile writes into vmlinux what its
/// recipe sees of the variables a caller could use to steer the compiler.
fn kernel_fixture(d: &Path) -> (PathBuf, PathBuf) {
    let src = d.join("ksrc/linux-0.0.1");
    write(
        &src.join("Makefile"),
        "olddefconfig:\n\t@true\nvmlinux:\n\t@printf 'kcflags=[%s] cc=[%s] cross=[%s] path=[%s]\\n' \
         \"$$KCFLAGS\" \"$(CC)\" \"$$CROSS_COMPILE\" \"$$PATH\" > vmlinux\n",
    );
    let dist = d.join("dist");
    std::fs::create_dir_all(&dist).unwrap();
    let st = Command::new("/usr/bin/tar")
        .arg("-C")
        .arg(d.join("ksrc"))
        .arg("-cJf")
        .arg(dist.join("linux-0.0.1.tar.xz"))
        .arg("linux-0.0.1")
        .status()
        .unwrap();
    assert!(st.success(), "setup: tar");
    let prof = d.join("prof");
    write(&prof.join("k.config"), "CONFIG_A=y\n");
    write(&prof.join("o.config"), "# overlay\nCONFIG_B=y\n");
    write(
        &prof.join("kernel.pin"),
        &format!(
            "KERNEL_VERSION=0.0.1\nKERNEL_TARBALL_SHA256={}\nKERNEL_CONFIG=k.config\n\
             KERNEL_CONFIG_SHA256={}\nKERNEL_OVERLAY=o.config\nKERNEL_OVERLAY_SHA256={}\n",
            sha(&dist.join("linux-0.0.1.tar.xz")),
            sha(&prof.join("k.config")),
            sha(&prof.join("o.config"))
        ),
    );
    (dist, prof)
}

fn kernel_step(r: &Path, dist: &Path, prof: &Path, env: &[(&str, String)]) -> Output {
    let mut c = gbe(r);
    c.arg("kernel")
        .arg(dist.join("kernel-build.json"))
        .arg(dist)
        .arg(prof);
    for (k, v) in env {
        c.env(k, v);
    }
    c.output().unwrap()
}

/// Round 4b, finding 3: the kernel's make runs in a constructed environment.
/// KCFLAGS, CC, CROSS_COMPILE and a PATH with a planted gcc/make exported by
/// whoever launched the build do not reach it. Control: vmlinux is built, and
/// the record names /usr/bin/make and the host gcc with digests.
#[test]
fn a_callers_kcflags_cc_or_path_do_not_reach_the_kernel_build() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let (dist, prof) = kernel_fixture(d.path());
    let evil = d.path().join("evil-bin");
    for t in ["make", "gcc", "cc"] {
        write(&evil.join(t), "#!/bin/sh\nexit 0\n");
        chmod_x(&evil.join(t));
    }
    let path = format!("{}:{}", evil.display(), std::env::var("PATH").unwrap());
    let o = kernel_step(
        &r,
        &dist,
        &prof,
        &[
            ("KCFLAGS", "-DEVIL".into()),
            ("CC", "/tmp/evil-cc".into()),
            ("CROSS_COMPILE", "evil-".into()),
            ("PATH", path),
        ],
    );
    assert!(
        o.status.success(),
        "control: the kernel builds: {}",
        text(&o)
    );
    let vml = std::fs::read_to_string(dist.join("vmlinux")).unwrap();
    assert!(
        !vml.to_lowercase().contains("evil"),
        "ATTACK: a caller's KCFLAGS/CC/CROSS_COMPILE/PATH reached the kernel build: {vml}"
    );
    let k: Value =
        serde_json::from_slice(&std::fs::read(dist.join("kernel-build.json")).unwrap()).unwrap();
    assert_eq!(k["tools"]["make"]["path"], "/usr/bin/make");
    assert!(k["tools"]["gcc"]["sha256"]
        .as_str()
        .is_some_and(|s| s.len() == 64));
    assert_eq!(k["vmlinux_sha256"], sha(&dist.join("vmlinux")));
}

/// Round 4b, finding 3: the kernel is built only from the pinned tarball,
/// config and overlay, each verified as the COPY the build then uses.
/// Control: a_callers_kcflags_cc_or_path_do_not_reach_the_kernel_build.
#[test]
fn a_kernel_from_sources_that_are_not_the_pinned_ones_is_refused() {
    for (attack, file) in [
        (
            "a tarball that is not the pinned one",
            "dist/linux-0.0.1.tar.xz",
        ),
        ("a config that is not the pinned one", "prof/k.config"),
        ("an overlay that is not the pinned one", "prof/o.config"),
    ] {
        let d = tempfile::tempdir().unwrap();
        let r = checkout(d.path());
        let (dist, prof) = kernel_fixture(d.path());
        if file.ends_with(".tar.xz") {
            // Another well-formed tarball, so only the pin can refuse it.
            let mk = d.path().join("ksrc/linux-0.0.1/Makefile");
            let s = std::fs::read_to_string(&mk).unwrap();
            write(&mk, &format!("# not the pinned source\n{s}"));
            let st = Command::new("/usr/bin/tar")
                .arg("-C")
                .arg(d.path().join("ksrc"))
                .arg("-cJf")
                .arg(dist.join("linux-0.0.1.tar.xz"))
                .arg("linux-0.0.1")
                .status()
                .unwrap();
            assert!(st.success(), "setup: tar");
        } else {
            let p = d.path().join(file);
            let mut b = std::fs::read(&p).unwrap();
            b.extend_from_slice(b"CONFIG_C=y\n");
            std::fs::write(&p, b).unwrap();
        }
        let o = kernel_step(&r, &dist, &prof, &[]);
        assert!(
            !o.status.success(),
            "ATTACK: the kernel was built from {attack}:\n{}",
            text(&o)
        );
        assert!(
            text(&o).contains("sha256 mismatch"),
            "{attack}: {}",
            text(&o)
        );
    }
}

// ── C9 round 5, FIELD-ORIGIN (amendment 80) ──────────────────────────────────

/// The triple the toolchain the build resolves says it runs on.
fn host_triple(repo: &Path) -> String {
    let o = Command::new("rustc")
        .arg("-vV")
        .current_dir(repo)
        .output()
        .unwrap();
    String::from_utf8_lossy(&o.stdout)
        .lines()
        .find_map(|l| l.strip_prefix("host: ").map(str::to_string))
        .expect("setup: rustc -vV names no host")
}

/// `python3 -c CODE SCRIPTS-DIR ARGS...` with guest_build_env imported as `g`.
fn gpy(repo: &Path, code: &str, args: &[&str]) -> Output {
    Command::new("python3")
        .arg("-B")
        .arg("-c")
        .arg(format!(
            "import json, sys\nsys.path.insert(0, sys.argv[1])\nimport guest_build_env as g\n{code}"
        ))
        .arg(repo.join("scripts"))
        .args(args)
        .output()
        .unwrap()
}

/// Round 5, BLOCKER: cargo's effective config is judged by its STRUCTURED key
/// path against the tree's committed keys, not by splitting the text cargo
/// prints. Cargo prints a `cfg(...)` target whose expression holds double quotes
/// with SINGLE quotes; the old split left a stray quote, read the table as a
/// harmless triple, and a committed `linker` under it linked the guest binaries
/// (a probe linker ran) while the record said foreign=[]. Each committed form
/// below must be refused by `begin`, and so must an ancestor's. Control: the
/// tree's own committed config (the two wasm rustflags) begins, foreign=[].
#[test]
fn a_committed_cargo_config_cannot_name_a_program_in_any_spelling() {
    let host = {
        let d = tempfile::tempdir().unwrap();
        host_triple(&checkout(d.path()))
    };
    let single = "\n[target.'cfg(all(target_os=\"linux\", target_env=\"musl\"))']\n\
                  linker = \"/tmp/evil-ld\"\n";
    let double = "\n[target.\"cfg(unix)\"]\nlinker = \"/tmp/evil-ld\"\n";
    let cases: Vec<(String, String, bool)> = vec![
        (
            "a single-quoted cfg(all(..=\"..\")) target (the form cargo prints with single quotes)"
                .into(),
            single.into(),
            true,
        ),
        ("a double-quoted cfg target".into(), double.into(), true),
        (
            "a cfg target's rustflags".into(),
            "\n[target.'cfg(unix)']\nrustflags = [\"--cfg\", \"evil\"]\n".into(),
            true,
        ),
        (
            "the host triple's linker".into(),
            format!("\n[target.{host}]\nlinker = \"/tmp/evil-ld\"\n"),
            true,
        ),
        (
            "the musl triple's linker".into(),
            "\n[target.x86_64-unknown-linux-musl]\nlinker = \"/tmp/evil-ld\"\n".into(),
            true,
        ),
        (
            "a wasm triple's linker (a committed key, but not an allowed one)".into(),
            "\n[target.wasm32-wasip1]\nlinker = \"/tmp/evil-ld\"\n".into(),
            true,
        ),
        (
            "a triple this host never builds, other than the committed ones".into(),
            "\n[target.aarch64-unknown-linux-gnu]\nlinker = \"/tmp/evil-ld\"\n".into(),
            true,
        ),
        (
            "[env]".into(),
            "\n[env]\nLD_PRELOAD = \"/tmp/evil.so\"\n".into(),
            true,
        ),
        (
            "[build] rustc".into(),
            "\n[build]\nrustc = \"/tmp/evil-rustc\"\n".into(),
            true,
        ),
        (
            "[build] rustflags".into(),
            "\n[build]\nrustflags = [\"--cfg\", \"evil\"]\n".into(),
            true,
        ),
        (
            "[build] target-dir".into(),
            "\n[build]\ntarget-dir = \"/tmp/reused\"\n".into(),
            true,
        ),
        (
            "[source] replacement".into(),
            "\n[source.crates-io]\nreplace-with = \"v\"\n[source.v]\ndirectory = \"/tmp/vendor\"\n"
                .into(),
            true,
        ),
        (
            "[patch]".into(),
            "\n[patch.crates-io]\nserde = { path = \"/tmp/serde\" }\n".into(),
            true,
        ),
        (
            "[registries]".into(),
            "\n[registries.x]\nindex = \"https://example.invalid/index\"\n".into(),
            true,
        ),
        ("[net]".into(), "\n[net]\noffline = true\n".into(), true),
        (
            "[http]".into(),
            "\n[http]\nproxy = \"http://example.invalid:1\"\n".into(),
            true,
        ),
        (
            "[profile]".into(),
            "\n[profile.release]\nopt-level = 1\n".into(),
            true,
        ),
        (
            "[unstable]".into(),
            "\n[unstable]\nbuild-std = [\"core\"]\n".into(),
            true,
        ),
        (
            "an ancestor's single-quoted cfg target".into(),
            single.into(),
            false,
        ),
        (
            "an ancestor's [env]".into(),
            "[env]\nLD_PRELOAD = \"/tmp/evil.so\"\n".into(),
            false,
        ),
        (
            "an ancestor's [source] replacement".into(),
            "[source.crates-io]\nreplace-with = \"v\"\n[source.v]\ndirectory = \"/tmp/vendor\"\n"
                .into(),
            false,
        ),
    ];
    for (attack, cfg, own) in &cases {
        let d = tempfile::tempdir().unwrap();
        let r = checkout(d.path());
        let scratch = private_scratch();
        let parent = scratch.path().join("parent");
        if *own {
            let p = r.join(".cargo/config.toml");
            let s = std::fs::read_to_string(&p).unwrap();
            write(&p, &format!("{s}{cfg}"));
            git(&r, &["add", "-A"]);
        } else {
            write(&scratch.path().join(".cargo/config.toml"), cfg);
        }
        let out = d.path().join("out");
        let o = build_env_only(
            &r,
            &out,
            &[("AXON_GUEST_BUILD_PARENT", parent.display().to_string())],
        );
        let rec = if o.status.success() {
            record(&out)
        } else {
            Value::Null
        };
        discard(&rec);
        assert!(
            !o.status.success(),
            "ATTACK: a cargo config the guest build would use was accepted ({attack}); the \
             record says foreign={}:\n{}",
            rec["effective_config"]["foreign"],
            text(&o)
        );
        assert!(
            text(&o).contains("effective configuration"),
            "{attack}: {}",
            text(&o)
        );
    }
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let out = d.path().join("out");
    let o = build_env_only(&r, &out, &[]);
    assert!(
        o.status.success(),
        "control: the tree's own committed config begins: {}",
        text(&o)
    );
    let rec = record(&out);
    discard(&rec);
    assert_eq!(rec["effective_config"]["foreign"], serde_json::json!([]));
}

/// The classifier itself, on the structured key path, for the spellings cargo
/// prints: it never splits text. A key is tolerated only when it is exactly one
/// of the committed keys AND its triple is neither a `cfg(...)` table nor one
/// the build compiles for (the host triple comes from `rustc -vV`).
#[test]
fn a_config_key_is_judged_by_its_structured_path_not_by_the_text_cargo_prints() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let host = host_triple(&r);
    let code = "\
triples = g.GUEST_TRIPLES | {sys.argv[2]}\n\
def p(*k): return g.key_problem(tuple(k), triples)\n\
out = {\n\
 'wasip1': p('target', 'wasm32-wasip1', 'rustflags'),\n\
 'unknown': p('target', 'wasm32-unknown-unknown', 'rustflags'),\n\
 'sq': p('target', 'cfg(all(target_os=\"linux\", target_env=\"musl\"))', 'linker'),\n\
 'sqflags': p('target', 'cfg(all(target_os=\"linux\", target_env=\"musl\"))', 'rustflags'),\n\
 'dq': p('target', 'cfg(unix)', 'linker'),\n\
 'host': p('target', sys.argv[2], 'rustflags'),\n\
 'musl': p('target', 'x86_64-unknown-linux-musl', 'rustflags'),\n\
 'other': p('target', 'aarch64-unknown-linux-gnu', 'rustflags'),\n\
 'wasmlinker': p('target', 'wasm32-wasip1', 'linker'),\n\
 'dotted': p('target', 'wasm32-wasip1.rustflags'),\n\
 'env': p('env', 'X'), 'build': p('build', 'rustc'), 'src': p('source', 'v', 'directory'),\n\
 'leaves': sorted(map(list, g.config_leaves({'a': {'b': [1]}, 'c': {}, 'd': 3}))),\n\
}\n\
print(json.dumps(out))";
    let o = gpy(&r, code, &[&host]);
    assert!(o.status.success(), "setup: {}", text(&o));
    let v: Value = serde_json::from_slice(&o.stdout).unwrap();
    // The triple guard, with an allowlist that (wrongly) names triples the build
    // compiles for: each is still refused, and the committed wasm key is not.
    let code_b = "\
g.COMMITTED_KEYS = {('target', sys.argv[2], 'rustflags'), ('target', 'cfg(unix)', 'linker'),\
 ('target', 'x86_64-unknown-linux-musl', 'rustflags'), ('target', 'wasm32-wasip1', 'rustflags')}\n\
triples = g.GUEST_TRIPLES | {sys.argv[2]}\n\
def p(*k): return g.key_problem(tuple(k), triples)\n\
print(json.dumps({'host': p('target', sys.argv[2], 'rustflags'), 'cfg': p('target', 'cfg(unix)', 'linker'),\
 'musl': p('target', 'x86_64-unknown-linux-musl', 'rustflags'), 'wasm': p('target', 'wasm32-wasip1', 'rustflags')}))";
    let o = gpy(&r, code_b, &[&host]);
    assert!(o.status.success(), "setup: {}", text(&o));
    let b: Value = serde_json::from_slice(&o.stdout).unwrap();
    assert!(b["wasm"].is_null(), "control: the wasm key passes: {b}");
    for k in ["host", "cfg", "musl"] {
        assert!(
            b[k].is_string(),
            "ATTACK: a committed key for a triple the build compiles for was tolerated ({k}): {b}"
        );
    }
    // The host triple is what `rustc -vV` says, not a constant; and a cargo that
    // cannot print its config refuses the build (it never reads as "no config").
    let fake = d.path().join("fake-bin");
    write(
        &fake.join("rustc"),
        "#!/bin/sh\necho 'rustc fake'\necho 'host: riscv64-fake-linux-gnu'\n",
    );
    write(
        &fake.join("cargo"),
        "#!/bin/sh\necho 'error: boom' >&2\nexit 1\n",
    );
    chmod_x(&fake.join("rustc"));
    chmod_x(&fake.join("cargo"));
    let code_c = "\
d = sys.argv[2]\n\
print(json.dumps({'host': g.host_triple(d + '/rustc'),\
 'cfg': g.effective_config(d + '/cargo', {'PATH': '/usr/bin:/bin'}, d)[1]}))";
    // A variable that survives into the constructed environment (cargo's own
    // list of environment variables that may affect the config does not name
    // RUSTFLAGS or RUSTC_WRAPPER) is refused; the constructed one is not.
    let code_d = "\
chan, cargo, rustc = g.toolchain()\n\
env = g.constructed_env('/tmp/none', cargo, rustc, {})\n\
bad = dict(env, CARGO_BUILD_RUSTC_WRAPPER='/w', RUSTFLAGS='-Cx', CARGO_ENCODED_RUSTFLAGS='x')\n\
print(json.dumps({'clean': g.effective_config(cargo, env, sys.argv[2])[1],\
 'bad': g.effective_config(cargo, bad, sys.argv[2])[1]}))";
    let o = gpy(&r, code_d, &[r.to_str().unwrap()]);
    assert!(o.status.success(), "setup: {}", text(&o));
    let e: Value = serde_json::from_slice(&o.stdout).unwrap();
    assert_eq!(
        e["clean"],
        serde_json::json!([]),
        "control: the constructed environment"
    );
    assert!(
        e["bad"].as_array().is_some_and(|a| a.len() == 3),
        "ATTACK: a CARGO_*/RUSTFLAGS variable in the constructed environment was accepted: {e}"
    );
    let o = gpy(&r, code_c, &[fake.to_str().unwrap()]);
    assert!(o.status.success(), "setup: {}", text(&o));
    let c: Value = serde_json::from_slice(&o.stdout).unwrap();
    assert_eq!(
        c["host"], "riscv64-fake-linux-gnu",
        "ATTACK: the host triple is not rustc's own"
    );
    assert!(
        c["cfg"]
            .as_array()
            .is_some_and(|a| a.iter().any(|x| x.as_str().unwrap().contains("failed"))),
        "ATTACK: a cargo that cannot print its config was read as having none: {c}"
    );
    // Control: exactly the committed keys are tolerated.
    assert!(
        v["wasip1"].is_null() && v["unknown"].is_null(),
        "control: the committed keys pass: {v}"
    );
    for k in [
        "sq",
        "sqflags",
        "dq",
        "host",
        "musl",
        "other",
        "wasmlinker",
        "dotted",
        "env",
        "build",
        "src",
    ] {
        assert!(
            v[k].is_string(),
            "ATTACK: the config key {k} was judged unable to reach the guest build: {v}"
        );
    }
    assert_eq!(
        v["leaves"],
        serde_json::json!([["a", "b"], ["c"], ["d"]]),
        "an empty table is a key somebody wrote"
    );
}

/// Round 6: the host binaries are built by a CONTROLLED step, so what the kit's
/// `check-host-build` judges is a constructed environment, never the caller's
/// ambient variables (round 5 listed some and missed AR_*, RANLIB_*, a planted
/// PATH, RUSTUP_HOME, CARGO ...): the same config in the same constructed
/// environment, from the clone, ancestors included. Control: junk in the
/// caller's environment changes nothing (it is dropped), a clean tree passes.
#[test]
fn the_host_build_configuration_is_judged_in_a_constructed_environment() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let check = |extra: &[(&str, String)], repo: &Path| -> Output {
        let mut c = gbe(repo);
        c.arg("check-host-build").arg(repo).env_clear();
        c.env("PATH", "/usr/bin:/bin")
            .env("HOME", std::env::var("HOME").unwrap());
        for (k, v) in extra {
            c.env(k, v);
        }
        c.output().unwrap()
    };
    let junk: Vec<(&str, String)> = vec![
        ("RUSTC_WRAPPER", "/tmp/w".into()),
        ("RUSTFLAGS", "--cfg evil".into()),
        ("AR_x86_64_unknown_linux_gnu", "/tmp/evil-ar".into()),
        ("RANLIB_x86_64_unknown_linux_gnu", "/tmp/evil-ranlib".into()),
        ("RUSTUP_HOME", "/tmp/evil-rustup".into()),
        ("RUST_TARGET_PATH", "/tmp/evil".into()),
        ("CRATE_CC_NO_DEFAULTS", "1".into()),
        ("PATH", "/tmp/evil-bin:/usr/bin:/bin".into()),
    ];
    let o = check(&junk, &r);
    assert!(
        o.status.success(),
        "control: the caller's ambient variables are dropped, not judged: {}",
        text(&o)
    );
    // A committed config naming a program, and an ancestor's, are refused.
    let single = "\n[target.'cfg(all(target_os=\"linux\", target_env=\"musl\"))']\nlinker = \"/tmp/evil-ld\"\n";
    let p = r.join(".cargo/config.toml");
    let orig = std::fs::read_to_string(&p).unwrap();
    write(&p, &format!("{orig}{single}"));
    let o = check(&[], &r);
    assert!(
        !o.status.success(),
        "ATTACK: a committed cfg target naming a linker passed the host build's config check:\n{}",
        text(&o)
    );
    write(&p, &orig);
    let scratch = private_scratch();
    write(
        &scratch.path().join(".cargo/config.toml"),
        "[build]\nrustc-wrapper = \"/usr/bin/sccache\"\n",
    );
    let inner = checkout(&scratch.path().join("deeper"));
    let o = check(&[], &inner);
    assert!(
        !o.status.success(),
        "ATTACK: an ancestor config naming a wrapper passed the host build's config check:\n{}",
        text(&o)
    );
}

/// Round 5, major-adjacent 2: the controlled record is the RUNNER's. Each
/// record below carries every field the structural judge reads and is refused
/// by the proof alone: no proof, a field edited after signing, a proof under a
/// key the builder did not make, a key file another uid could read, a key
/// that is a symlink, a key that is gone. Control: the record `begin` wrote.
#[test]
fn a_build_record_its_runner_did_not_sign_is_refused() {
    let d = tempfile::tempdir().unwrap();
    // Its own build parent: this test changes its key's and its key directory's
    // modes, which the default parent's concurrent builds must never see.
    let scratch = private_scratch();
    let r = checkout(d.path());
    let out = d.path().join("out");
    let o = build_env_only(
        &r,
        &out,
        &[(
            "AXON_GUEST_BUILD_PARENT",
            scratch.path().join("parent").display().to_string(),
        )],
    );
    assert!(o.status.success(), "setup: begin: {}", text(&o));
    let rec = record(&out);
    let rec_path = out.join("build-env.json");
    let key = Path::new(rec["build_parent"].as_str().unwrap())
        .join("keys")
        .join(format!("{}.key", rec["proof"]["id"].as_str().unwrap()));
    let code = "\
rec = json.load(open(sys.argv[2]))\n\
mode = sys.argv[3]\n\
import os\n\
exp = (os.geteuid(), rec['build_parent'])\n\
if mode == 'none': rec.pop('proof')\n\
elif mode == 'edit': rec['artifacts']['axon'] = 'f' * 64\n\
elif mode == 'forged': import hmac as h; rec['proof']['hmac'] = h.new(b'x' * 32, g.proof_payload(rec), 'sha256').hexdigest()\n\
elif mode == 'otherparent': rec['build_parent'] = '/var/tmp'\n\
elif mode == 'plantedparent':\n\
\x20import hmac as h, tempfile, os\n\
\x20par = tempfile.mkdtemp(); os.chmod(par, 0o1777); os.mkdir(par + '/keys', 0o700)\n\
\x20open(par + '/keys/mine.key', 'w').write('k' * 64); os.chmod(par + '/keys/mine.key', 0o400)\n\
\x20rec['build_parent'] = par; rec['proof']['id'] = 'mine'\n\
\x20rec['proof']['hmac'] = h.new(b'k' * 64, g.proof_payload(rec), 'sha256').hexdigest()\n\
\x20exp = (os.geteuid(), par)\n\
elif mode in ('forgedaccount', 'forgedpinned'):\n\
\x20import hmac as h, tempfile\n\
\x20par = tempfile.mkdtemp(dir=os.path.dirname(rec['build_parent']), prefix='axon-forge-'); os.chmod(par, 0o700); os.chown(par, 65534, 65534)\n\
\x20os.mkdir(par + '/keys', 0o700); os.chown(par + '/keys', 65534, 65534)\n\
\x20open(par + '/keys/forged.key', 'w').write('f' * 64); os.chown(par + '/keys/forged.key', 65534, 65534); os.chmod(par + '/keys/forged.key', 0o400)\n\
\x20rec['builder_uid'] = 65534; rec['build_parent'] = par; rec['proof']['id'] = 'forged'\n\
\x20rec['proof']['hmac'] = h.new(b'f' * 64, g.proof_payload(rec), 'sha256').hexdigest()\n\
\x20if mode == 'forgedpinned': exp = (65534, par)\n\
out = g.proof_problems(rec, 'build', exp)\n\
import shutil\n\
if mode in ('plantedparent', 'forgedaccount', 'forgedpinned'): shutil.rmtree(rec['build_parent'])\n\
print(json.dumps(out))";
    let judge = |mode: &str| -> String {
        let o = gpy(&r, code, &[rec_path.to_str().unwrap(), mode]);
        assert!(o.status.success(), "setup: {mode}: {}", text(&o));
        serde_json::from_slice::<String>(&o.stdout).unwrap()
    };
    let mut failures = vec![];
    assert!(
        unsafe { libc::geteuid() } == 0,
        "setup: the forge cases chown a directory to another account (run as root)"
    );
    assert_eq!(
        judge("same"),
        "",
        "control: the record the runner wrote holds"
    );
    assert_eq!(
        judge("forgedpinned"),
        "",
        "control: the forged record IS accepted by a judge whose pin names the forger (the pin is the barrier)"
    );
    for (mode, why) in [
        ("none", "no builder proof"),
        ("edit", "does not hold"),
        ("forged", "does not hold"),
        ("otherparent", "does not hold"),
        // The reviewer's forge (round 6): a record naming ANOTHER account and
        // that account's own private directory, signed under its own key. Only
        // the judge's expectation of who builds refuses it.
        ("forgedaccount", "cannot be checked"),
    ] {
        let got = judge(mode);
        if !got.contains(why) {
            failures.push(format!("{mode}: {got:?}"));
        }
    }
    // The key's own protection.
    let saved = std::fs::read(&key).unwrap();
    chmod(&key, 0o644);
    let open = judge("same");
    chmod(&key, 0o400);
    // A symlink to a file that is otherwise a perfectly good key (0400, ours,
    // the same bytes): only refusing to FOLLOW it refuses this.
    let twin = d.path().join("twin.key");
    std::fs::write(&twin, &saved).unwrap();
    chmod(&twin, 0o400);
    std::fs::remove_file(&key).unwrap();
    std::os::unix::fs::symlink(&twin, &key).unwrap();
    let linked = judge("same");
    std::fs::remove_file(&key).unwrap();
    std::fs::write(&key, &saved).unwrap();
    chmod(&key, 0o400);
    let keys_dir = key.parent().unwrap();
    chmod(keys_dir, 0o755);
    let enterable = judge("same");
    chmod(keys_dir, 0o700);
    std::fs::remove_file(&key).unwrap();
    let gone = judge("same");
    std::fs::write(&key, saved).unwrap();
    chmod(&key, 0o400);
    // A record somebody wrote and signed under a key of their own in a parent
    // they can write (a world-writable one): the key checks all pass; only the
    // parent's privacy refuses it.
    let planted = judge("plantedparent");
    // The key (and then its directory) belongs to ANOTHER account.
    let chown = |p: &Path, uid: u32| {
        std::os::unix::fs::chown(p, Some(uid), None).unwrap();
    };
    chown(&key, 65534);
    let foreign_key = judge("same");
    chown(&key, 0);
    chown(keys_dir, 65534);
    let foreign_dir = judge("same");
    chown(keys_dir, 0);
    discard(&rec);
    for (what, got) in [
        ("a key another uid can read", open),
        ("a key that is a symlink", linked),
        ("a key in a directory others can enter", enterable),
        ("a key that is gone", gone),
        ("a hand-signed record in a world-writable parent", planted),
        ("a key owned by another account", foreign_key),
        ("a key directory owned by another account", foreign_dir),
    ] {
        if !got.contains("cannot be checked") {
            failures.push(format!("{what}: {got:?}"));
        }
    }
    assert!(
        failures.is_empty(),
        "ATTACK: a guest build record its runner did not sign passed the proof: {failures:?}"
    );
}

/// Round 5: `dist` records the digest of EVERY artifact of the image and
/// refuses a copy that is not the controlled step's output; the manifest and
/// the freeze take digests from the record (`dist_problems`), refuse a dist
/// file that differs, and refuse a record without the runner's proof. Control:
/// the honest dist is accepted.
#[test]
fn a_dist_file_the_controlled_runner_did_not_produce_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, _) = begun(d.path());
    finished(&r, &rec_path);
    let sq = d.path().join("rootfs.sqfs");
    let o = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .output()
        .unwrap();
    assert!(o.status.success(), "setup: rootfs: {}", text(&o));
    let dist = d.path().join("dist");
    std::fs::create_dir_all(&dist).unwrap();
    std::fs::copy(&sq, dist.join("rootfs.sqfs")).unwrap();
    for n in ["axon", "axon-guest-init", "axon-psv-runner"] {
        std::fs::copy(gpath(&r, &rec_path, n), dist.join(n)).unwrap();
    }
    let honest = std::fs::read(dist.join("axon")).unwrap();
    // A binary built elsewhere, copied over the controlled one.
    std::fs::write(dist.join("axon"), b"#!/bin/sh\necho built elsewhere\n").unwrap();
    let o = gbe(&r)
        .arg("dist")
        .arg(&rec_path)
        .arg(&dist)
        .output()
        .unwrap();
    let swapped_recorded = o.status.success();
    std::fs::write(dist.join("axon"), &honest).unwrap();
    let c = gbe(&r)
        .arg("dist")
        .arg(&rec_path)
        .arg(&dist)
        .output()
        .unwrap();
    let rec: Value = serde_json::from_slice(&std::fs::read(&rec_path).unwrap()).unwrap();
    let code = "\
import os\n\
rec = json.load(open(sys.argv[2]))\n\
if sys.argv[4] == 'handwritten': rec.pop('proof')\n\
print(json.dumps(g.dist_problems(sys.argv[3], rec, None, (os.geteuid(), rec['build_parent']))))";
    let judge = |mode: &str| -> String {
        let o = gpy(
            &r,
            code,
            &[rec_path.to_str().unwrap(), dist.to_str().unwrap(), mode],
        );
        assert!(o.status.success(), "setup: {mode}: {}", text(&o));
        serde_json::from_slice::<String>(&o.stdout).unwrap()
    };
    let control = judge("same");
    let hand = judge("handwritten");
    std::fs::write(dist.join("rootfs.sqfs"), b"squashed elsewhere").unwrap();
    let swapped = judge("same");
    discard(&rec);
    assert!(
        !swapped_recorded,
        "ATTACK: a dist binary the controlled build did not produce was recorded:\n{}",
        text(&o)
    );
    assert!(text(&o).contains("is not the bytes"), "{}", text(&o));
    assert!(c.status.success(), "control: dist records: {}", text(&c));
    assert_eq!(control, "", "control: the honest dist is accepted");
    assert!(
        hand.contains("no builder proof"),
        "ATTACK: a hand-written record named dist digests and was accepted: {hand:?}"
    );
    assert!(
        swapped.contains("rootfs.sqfs is not the bytes"),
        "ATTACK: a dist file that differs from the record was accepted: {swapped:?}"
    );
    assert_eq!(rec["dist"]["axon"], sha(&dist.join("axon")));
}

/// Round 5: the kernel build's record is signed by its runner too, and a field
/// edited afterwards (the digest of a vmlinux built elsewhere) breaks it.
#[test]
fn a_kernel_build_record_edited_after_its_runner_signed_it_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let (dist, prof) = kernel_fixture(d.path());
    let o = kernel_step(&r, &dist, &prof, &[]);
    assert!(o.status.success(), "setup: kernel: {}", text(&o));
    let kpath = dist.join("kernel-build.json");
    let kparent: Value = serde_json::from_slice(&std::fs::read(&kpath).unwrap()).unwrap();
    assert!(
        !Path::new(kparent["build_parent"].as_str().unwrap()).starts_with(real_parent()),
        "ATTACK: a test built a kernel under the real builder-private parent"
    );
    let code = "\
import os\n\
rec = json.load(open(sys.argv[2]))\n\
if sys.argv[3] == 'edit': rec['vmlinux_sha256'] = 'f' * 64\n\
print(json.dumps(g.proof_problems(rec, 'kernel build', (os.geteuid(), rec['build_parent']))))";
    let judge = |mode: &str| -> String {
        let o = gpy(&r, code, &[kpath.to_str().unwrap(), mode]);
        assert!(o.status.success(), "setup: {mode}: {}", text(&o));
        serde_json::from_slice::<String>(&o.stdout).unwrap()
    };
    let (control, edited) = (judge("same"), judge("edit"));
    assert_eq!(
        control, "",
        "control: the kernel record the runner wrote holds"
    );
    assert!(
        edited.contains("does not hold"),
        "ATTACK: a kernel record edited after signing was accepted: {edited:?}"
    );
}

// ── C9 round 6, FIELD-ORIGIN (amendment 86): the host binaries' controlled build ──

const HOST_BINS: [&str; 4] = [
    "axon-fabric",
    "axon-protected-launcher",
    "axon-custodian",
    "axon-observer",
];

/// A committed checkout whose one package is named `axon-fabric` and has the
/// four host binaries (no dependencies): what the fixed host invocation
/// `cargo build --release --locked -p axon-fabric --bins` builds.
fn host_checkout(parent: &Path) -> PathBuf {
    let r = parent.join("hrepo");
    for f in COPIED {
        write(
            &r.join(f),
            &std::fs::read_to_string(repo_root().join(f)).unwrap(),
        );
    }
    write(
        &r.join("Cargo.toml"),
        "[workspace]\nmembers = [\"fabric\"]\nresolver = \"2\"\n",
    );
    let mut bins = String::new();
    for b in HOST_BINS {
        bins.push_str(&format!(
            "[[bin]]\nname = \"{b}\"\npath = \"src/bin/{b}.rs\"\n"
        ));
        write(&r.join(format!("fabric/src/bin/{b}.rs")), "fn main() {}\n");
    }
    write(
        &r.join("fabric/Cargo.toml"),
        &format!(
            "[package]\nname = \"axon-fabric\"\nversion = \"0.0.0\"\nedition = \"2021\"\n{bins}"
        ),
    );
    write(
        &r.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual \
         editing.\nversion = 4\n\n[[package]]\nname = \"axon-fabric\"\nversion = \"0.0.0\"\n",
    );
    git(&r, &["init", "-q", "-b", "main"]);
    git(&r, &["add", "-A"]);
    git(&r, &["commit", "-q", "-m", "host fixture"]);
    r
}

fn head_of(r: &Path) -> String {
    let o = Command::new("/usr/bin/git")
        .arg("-C")
        .arg(r)
        .args(["rev-parse", "HEAD"])
        .output()
        .unwrap();
    String::from_utf8_lossy(&o.stdout).trim().to_string()
}

fn host_build(repo: &Path, out: &Path, env: &[(&str, String)]) -> Output {
    let mut c = gbe(repo);
    c.arg("host-build").arg(out);
    for (k, v) in env {
        c.env(k, v);
    }
    c.output().unwrap()
}

fn host_record(out: &Path) -> Value {
    serde_json::from_slice(&std::fs::read(out.join("host-build.json")).unwrap()).unwrap()
}

/// Round 6, BLOCKER 2 (executed by the reviewer): `build_state` was read only by
/// axon-fabric's build.rs, so a build under RUSTC_WRAPPER compiled every
/// dependency wrapped before that build.rs refused, and an honest-looking retry
/// in the same target dir linked them. The host binaries now come from a
/// CONTROLLED build: a fresh clone, a fresh EMPTY target dir and CARGO_HOME every
/// time, the constructed environment (fixed PATH, the pinned rustc, nothing
/// inherited), one fixed invocation. The caller's wrapper, flags and a `cc`
/// planted on its PATH never reach it; a second build shares nothing with the
/// first. Control: the clean build succeeds, its binaries are what the signed
/// record names, and the record names the clone's revision and the linker.
#[test]
fn a_callers_wrapper_flags_or_planted_cc_never_reach_the_controlled_host_build() {
    let d = tempfile::tempdir().unwrap();
    let r = host_checkout(d.path());
    let out_a = d.path().join("host-a");
    let a = host_build(&r, &out_a, &[]);
    assert!(
        a.status.success(),
        "control: the host build builds: {}",
        text(&a)
    );
    let rec_a = host_record(&out_a);
    // The attack: every input the reviewer used, in the caller's environment.
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker).display().to_string();
    let evil = d.path().join("evil-bin");
    let cc_marker = d.path().join("cc-ran");
    write(
        &evil.join("cc"),
        &format!(
            "#!/bin/sh\n: > '{}'\nexec /usr/bin/cc \"$@\"\n",
            cc_marker.display()
        ),
    );
    chmod_x(&evil.join("cc"));
    let evil_path = format!("{}:{}", evil.display(), std::env::var("PATH").unwrap());
    let out_b = d.path().join("host-b");
    let b = host_build(
        &r,
        &out_b,
        &[
            ("RUSTC_WRAPPER", w.clone()),
            ("RUSTC_WORKSPACE_WRAPPER", w.clone()),
            ("CARGO_BUILD_RUSTC_WRAPPER", w),
            ("RUSTFLAGS", "--cfg evil".into()),
            ("PATH", evil_path),
            ("CARGO", "/tmp/evil-cargo".into()),
            ("AR_x86_64_unknown_linux_gnu", "/tmp/evil-ar".into()),
        ],
    );
    let (wrapped, planted) = (marker.exists(), cc_marker.exists());
    assert!(
        !wrapped,
        "ATTACK: a caller's RUSTC_WRAPPER reached the controlled host build:\n{}",
        text(&b)
    );
    assert!(
        !planted,
        "ATTACK: a cc planted on the caller's PATH linked the controlled host build:\n{}",
        text(&b)
    );
    assert!(
        b.status.success(),
        "control: the build with the junk environment still builds (it is dropped): {}",
        text(&b)
    );
    let rec_b = host_record(&out_b);
    // Nothing is shared between two builds: a different target dir each time,
    // already removed, so a retry can never link an earlier build's artifacts.
    assert_ne!(rec_a["target_dir"], rec_b["target_dir"]);
    assert!(!Path::new(rec_b["target_dir"].as_str().unwrap()).exists());
    assert_eq!(rec_b["target_dir_created_empty"], true);
    assert_eq!(
        rec_b["source_revision"],
        head_of(&r),
        "the clone's revision"
    );
    for n in HOST_BINS {
        assert_eq!(rec_b["artifacts"][n], sha(&out_b.join(n)), "{n}");
    }
    for t in ["cc", "ld"] {
        assert!(
            rec_b["toolchain"]["host_tools"][t]["sha256"]
                .as_str()
                .is_some_and(|s| s.len() == 64)
                && rec_b["toolchain"]["host_tools"][t]["path"]
                    .as_str()
                    .is_some_and(|p| p.starts_with("/usr/bin/") || p.starts_with("/bin/")),
            "the record names the linker tool {t} by absolute path and digest: {}",
            rec_b["toolchain"]["host_tools"]
        );
    }
    // The planted cc was not the recorded linker.
    assert!(!rec_b["toolchain"]["host_tools"]["cc"]["path"]
        .as_str()
        .unwrap()
        .contains("evil"));
}

/// Round 6: the kit installs host binaries only from a directory whose
/// `host-build.json` the PINNED builder signed. Each record below is refused by
/// that and nothing else: binaries replaced, a record edited afterwards, no
/// proof, no record, extra files, the wrong revision, a judge expecting another
/// builder, and the reviewer's forge (a record naming another account and its
/// own private directory, signed under its own key). Control: the honest
/// directory is accepted by the judge that expects its builder.
#[test]
fn a_host_build_directory_the_pinned_builder_did_not_make_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let r = host_checkout(d.path());
    let out = d.path().join("host");
    let o = host_build(&r, &out, &[]);
    assert!(o.status.success(), "setup: host build: {}", text(&o));
    assert!(
        unsafe { libc::geteuid() } == 0,
        "setup: the forge case chowns a directory to another account (run as root)"
    );
    let rec = host_record(&out);
    let parent = rec["build_parent"].as_str().unwrap().to_string();
    let head = head_of(&r);
    let code = "\
import os, shutil, hmac as h, tempfile\n\
src, mode, commit, parent = sys.argv[2:6]\n\
d = tempfile.mkdtemp(); out = d + '/o'; shutil.copytree(src, out)\n\
rp = out + '/host-build.json'; rec = json.load(open(rp))\n\
exp = (os.geteuid(), parent)\n\
def save(): json.dump(rec, open(rp, 'w'))\n\
if mode == 'binary': open(out + '/axon-observer', 'wb').write(b'built elsewhere')\n\
elif mode == 'edit': rec['source_revision'] = 'a' * 40; save()\n\
elif mode == 'noproof': rec.pop('proof'); save()\n\
elif mode == 'norecord': os.remove(rp)\n\
elif mode == 'extra': open(out + '/evil', 'w').write('x')\n\
elif mode == 'nobuild': rec['builds'] = []; g.write(rp, rec)\n\
elif mode == 'dropped':\n\
\x20del rec['artifacts']['axon-observer']; g.write(rp, rec); os.remove(out + '/axon-observer')\n\
elif mode == 'symlink':\n\
\x20shutil.copy(out + '/axon-fabric', d + '/twin'); os.remove(out + '/axon-fabric'); os.symlink(d + '/twin', out + '/axon-fabric')\n\
elif mode == 'builder': exp = (os.geteuid() + 1, parent)\n\
elif mode == 'parent': exp = (os.geteuid(), '/var/tmp')\n\
elif mode == 'forge':\n\
\x20par = tempfile.mkdtemp(dir=os.path.dirname(parent), prefix='axon-forge-'); os.chmod(par, 0o700); os.chown(par, 65534, 65534)\n\
\x20os.mkdir(par + '/keys', 0o700); os.chown(par + '/keys', 65534, 65534)\n\
\x20open(par + '/keys/f.key', 'w').write('f' * 64); os.chown(par + '/keys/f.key', 65534, 65534); os.chmod(par + '/keys/f.key', 0o400)\n\
\x20anc, why = g.ancestors_of(par, 65534); assert not why, why\n\
\x20rec = json.loads(json.dumps(rec).replace(parent, par)); rec['builder_uid'] = 65534; rec['build_parent_ancestors'] = anc; rec['proof']['id'] = 'f'\n\
\x20rec['proof']['hmac'] = h.new(b'f' * 64, g.proof_payload(rec), 'sha256').hexdigest(); save()\n\
res = g.host_record_problems(out, exp, None if mode in ('nocommit', 'edit') else (('b' * 40) if mode == 'revision' else commit))\n\
shutil.rmtree(d)\n\
if mode == 'forge': shutil.rmtree(par)\n\
print(json.dumps(res))";
    let judge = |mode: &str| -> String {
        let o = gpy(&r, code, &[out.to_str().unwrap(), mode, &head, &parent]);
        assert!(o.status.success(), "setup: {mode}: {}", text(&o));
        serde_json::from_slice::<String>(&o.stdout).unwrap()
    };
    assert_eq!(
        judge("same"),
        "",
        "control: the honest host build is accepted"
    );
    let mut failures = vec![];
    for (mode, why) in [
        (
            "binary",
            "is not the bytes the controlled host build recorded",
        ),
        ("edit", "does not hold"),
        ("noproof", "no builder proof"),
        ("norecord", "holds no readable host-build.json"),
        ("extra", "files the controlled host build did not make"),
        ("revision", "was made from revision"),
        ("nobuild", "not exactly the one controlled host invocation"),
        ("dropped", "names no digest for exactly"),
        (
            "symlink",
            "is not the bytes the controlled host build recorded",
        ),
        ("builder", "cannot be checked"),
        ("parent", "cannot be checked"),
        ("forge", "cannot be checked"),
    ] {
        let got = judge(mode);
        if !got.contains(why) {
            failures.push(format!("{mode}: {got:?}"));
        }
    }
    assert!(
        failures.is_empty(),
        "ATTACK: a host build directory the pinned builder did not make was accepted: {failures:?}"
    );
}

/// Round 6: the host build writes a NEW directory, and its cargo invocation is
/// the one fixed entry: the guest table's invocations are not the host's, and
/// the host's are not the guest's.
#[test]
fn the_host_build_runs_one_fixed_invocation_into_a_new_directory() {
    let d = tempfile::tempdir().unwrap();
    let r = host_checkout(d.path());
    let out = d.path().join("host");
    std::fs::create_dir_all(&out).unwrap();
    let o = host_build(&r, &out, &[]);
    assert!(
        !o.status.success() && text(&o).contains("exists"),
        "ATTACK: the host build wrote into an existing directory: {}",
        text(&o)
    );
    // A guest record refuses the host's invocation (it is not in the guest table).
    let (gr, rec_path, rec) = begun(d.path());
    let o = gcargo(
        &gr,
        &rec_path,
        None,
        &[
            "build",
            "--release",
            "--locked",
            "-p",
            "axon-fabric",
            "--bins",
            "--quiet",
        ],
    );
    discard(&rec);
    assert!(
        !o.status.success() && text(&o).contains("not a controlled guest build invocation"),
        "ATTACK: a guest build ran the host build's invocation: {}",
        text(&o)
    );
}
