//! The protected guest image is built in an environment the build CONSTRUCTS
//! (scripts/guest_build_env.py), not one it filters by a list of names
//! (C9 round 4, FIELD-ORIGIN / PSV-2 / EQUIVALENCE; two reviewers built
//! through an ancestor `.cargo/config.toml`, a dotted `build.rustc-wrapper`,
//! RUSTC/RUSTFLAGS and a reused target dir, and the old guard passed each).
//!
//! C9 round 4b (FIELD-ORIGIN, amendment 63): the build runs on a PRIVATE copy
//! of the tracked tree under a directory only root or the builder can write,
//! with cargo's effective config held to begin's before and after EVERY
//! invocation; only the table's exact invocations run; and the kernel and the
//! rootfs are made in the same discipline.
//!
//! These run the PRODUCTION route: `scripts/build-guest-image.sh
//! --build-env-only`, the same `gcargo_begin` every guest build starts with,
//! and the `guest_build_env.py cargo` / `rootfs` / `kernel` steps the image
//! build calls, from a scratch checkout of this tree's files.

#[path = "../../axon-core/tests/script_spawn/mod.rs"]
mod script_spawn;
use script_spawn::{repo_root, Bins};
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};

/// The files the controlled-build step reads, copied from THIS tree.
const COPIED: [&str; 4] = [
    "scripts/build-guest-image.sh",
    "scripts/guest_build_env.py",
    "rust-toolchain.toml",
    ".cargo/config.toml",
];
const CRT: &str = "-C target-feature=+crt-static";
/// The protected `axon-guest-init` invocation (guest_build_env.py
/// PROTECTED_BUILDS), exactly: the checkout's one crate has that name.
const GUEST_INIT: [&str; 8] = [
    "build",
    "--locked",
    "-p",
    "axon-guest-init",
    "--target",
    "x86_64-unknown-linux-musl",
    "--release",
    "--quiet",
];

fn write(p: &Path, s: &str) {
    std::fs::create_dir_all(p.parent().unwrap()).unwrap();
    std::fs::write(p, s).unwrap();
}

fn chmod(p: &Path, mode: u32) {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(p, std::fs::Permissions::from_mode(mode)).unwrap();
}

fn chmod_x(p: &Path) {
    chmod(p, 0o755);
}

fn sha(p: &Path) -> String {
    format!("{:x}", Sha256::digest(std::fs::read(p).unwrap()))
}

fn git(r: &Path, args: &[&str]) {
    let st = Command::new("/usr/bin/git")
        .arg("-C")
        .arg(r)
        .args(["-c", "user.name=t", "-c", "user.email=t@example"])
        .args(args)
        .stdout(Stdio::null())
        .status()
        .unwrap();
    assert!(st.success(), "git {args:?}");
}

/// A git checkout at `<parent>/repo` holding the build's files and a one-crate
/// workspace whose crate is named `axon-guest-init` (no dependencies, so a
/// fresh CARGO_HOME builds it offline), plus a rootfs profile whose busybox
/// is a fixture at `<parent>/busybox`. The build copies its TRACKED files.
fn checkout(parent: &Path) -> PathBuf {
    let r = parent.join("repo");
    for f in COPIED {
        write(
            &r.join(f),
            &std::fs::read_to_string(repo_root().join(f)).unwrap(),
        );
    }
    write(
        &r.join("Cargo.toml"),
        "[workspace]\nmembers = [\"guest\"]\nresolver = \"2\"\n",
    );
    write(
        &r.join("guest/Cargo.toml"),
        "[package]\nname = \"axon-guest-init\"\nversion = \"0.0.0\"\nedition = \"2021\"\n",
    );
    write(&r.join("guest/src/main.rs"), "fn main() {}\n");
    write(
        &r.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual \
         editing.\nversion = 4\n\n[[package]]\nname = \"axon-guest-init\"\nversion = \"0.0.0\"\n",
    );
    let bb = parent.join("busybox");
    write(&bb, "#!/bin/sh\necho sh\necho ls\necho busybox\n");
    chmod_x(&bb);
    write(
        &r.join("profiles/linux-microvm/kernel.pin"),
        &format!(
            "BUSYBOX_SRC={}\nBUSYBOX_SHA256={}\n",
            bb.display(),
            sha(&bb)
        ),
    );
    write(
        &r.join("profiles/linux-microvm/guest-init.sh"),
        "#!/bin/sh\necho init\n",
    );
    git(&r, &["init", "-q", "-b", "main"]);
    git(&r, &["add", "-A"]);
    r
}

/// `build-guest-image.sh --build-env-only <out>`: the controlled environment
/// alone, recorded in `<out>/build-env.json`.
fn build_env_only(repo: &Path, out: &Path, env: &[(&str, String)]) -> Output {
    let mut c = script_spawn::script(
        "bash",
        repo.join("scripts/build-guest-image.sh"),
        Bins::BuildsItsOwn,
    );
    c.arg("--build-env-only").arg(out).current_dir(repo);
    for (k, v) in env {
        c.env(k, v);
    }
    c.output().unwrap()
}

/// `guest_build_env.py ...` from the checkout.
fn gbe(repo: &Path) -> Command {
    let mut c = script_spawn::script(
        "python3",
        repo.join("scripts/guest_build_env.py"),
        Bins::BuildsItsOwn,
    );
    c.current_dir(repo);
    c
}

/// `guest_build_env.py cargo REC [--rustflags F] -- ARGS`: one controlled step.
fn gcargo(repo: &Path, rec: &Path, rustflags: Option<&str>, args: &[&str]) -> Output {
    let mut c = gbe(repo);
    c.arg("cargo").arg(rec);
    if let Some(f) = rustflags {
        c.args(["--rustflags", f]);
    }
    c.arg("--").args(args);
    c.output().unwrap()
}

fn record(out: &Path) -> Value {
    serde_json::from_slice(&std::fs::read(out.join("build-env.json")).unwrap()).unwrap()
}

/// The private build directory (the parent of the fresh target dir).
fn base_of(rec: &Value) -> PathBuf {
    Path::new(rec["target_dir"].as_str().unwrap())
        .parent()
        .unwrap()
        .to_path_buf()
}

/// Remove the private build directory a successful begin created.
fn discard(rec: &Value) {
    if rec["target_dir"].as_str().is_some() {
        let base = base_of(rec);
        if base
            .file_name()
            .is_some_and(|n| n.to_string_lossy().starts_with("axon-guest-build-"))
        {
            let _ = std::fs::remove_dir_all(base);
        }
    }
}

fn text(o: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&o.stdout),
        String::from_utf8_lossy(&o.stderr)
    )
}

/// A scratch directory under the builder's home: its ancestors are only
/// root's or the builder's, so it may hold a build parent.
fn private_scratch() -> tempfile::TempDir {
    let cache = PathBuf::from(std::env::var("HOME").unwrap()).join(".cache");
    std::fs::create_dir_all(&cache).unwrap();
    tempfile::tempdir_in(cache).unwrap()
}

/// A rustc wrapper that leaves `marker` behind and runs the compiler.
fn wrapper(dir: &Path, marker: &Path) -> PathBuf {
    let w = dir.join("wrapper");
    write(
        &w,
        &format!("#!/bin/sh\n: > '{}'\nexec \"$@\"\n", marker.display()),
    );
    chmod_x(&w);
    w
}

/// A begun controlled build of a fresh checkout under `d`: (repo, record path, record).
fn begun(d: &Path) -> (PathBuf, PathBuf, Value) {
    let r = checkout(d);
    let out = d.join("out");
    let o = build_env_only(&r, &out, &[]);
    assert!(o.status.success(), "setup: begin: {}", text(&o));
    let rec = record(&out);
    (r, out.join("build-env.json"), rec)
}

/// cargo's EFFECTIVE configuration, as it resolves it from the build's
/// directory, may hold nothing the guest build would use -- from an ancestor
/// directory's config, in the dotted-key spelling, or committed to the tree's
/// own config. Control: the tree's own config (wasm-only rustflags) passes.
#[test]
fn a_cargo_config_setting_the_guest_build_would_use_is_refused() {
    let cases: [(&str, &str, bool); 5] = [
        (
            "an ancestor .cargo/config.toml naming a rustc wrapper",
            "[build]\nrustc-wrapper = \"/usr/bin/sccache\"\n",
            false,
        ),
        (
            "an ancestor config in the dotted-key spelling",
            "build.rustc-wrapper = \"/usr/bin/sccache\"\n",
            false,
        ),
        (
            "an ancestor config naming a linker for the guest's target",
            "[target.x86_64-unknown-linux-musl]\nlinker = \"/tmp/evil-cc\"\n",
            false,
        ),
        (
            "an ancestor config adding rustflags",
            "[build]\nrustflags = [\"--cfg\", \"evil\"]\n",
            false,
        ),
        (
            "the tree's own config naming a rustc",
            "build.rustc = \"/tmp/evil-rustc\"\n",
            true,
        ),
    ];
    for (attack, cfg, own) in cases {
        let d = tempfile::tempdir().unwrap();
        let r = checkout(d.path());
        // The build parent's ancestors are where cargo, running in the private
        // copy, looks: a config there (written by root or the builder, the
        // only uids that can) is in its effective configuration.
        let scratch = private_scratch();
        let parent = scratch.path().join("parent");
        if own {
            let p = r.join(".cargo/config.toml");
            // At the top, so the dotted key is not inside the file's tables.
            let s = std::fs::read_to_string(&p).unwrap();
            write(&p, &format!("{cfg}{s}"));
            git(&r, &["add", "-A"]);
        } else {
            write(&scratch.path().join(".cargo/config.toml"), cfg);
        }
        let out = d.path().join("out");
        let o = build_env_only(
            &r,
            &out,
            &[("AXON_GUEST_BUILD_PARENT", parent.display().to_string())],
        );
        if o.status.success() {
            discard(&record(&out));
        }
        assert!(
            !o.status.success(),
            "ATTACK: the guest build ran under a cargo config setting it would use ({attack}):\n{}",
            text(&o)
        );
        assert!(
            text(&o).contains("effective configuration"),
            "{attack}: {}",
            text(&o)
        );
    }
    // Control: the tree's own config alone.
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let out = d.path().join("out");
    let o = build_env_only(&r, &out, &[]);
    assert!(
        o.status.success(),
        "control: the tree's own config builds: {}",
        text(&o)
    );
    let rec = record(&out);
    discard(&rec);
    assert_eq!(rec["effective_config"]["foreign"], serde_json::json!([]));
}

/// Cargo runs in the environment the build constructs, never the caller's:
/// a RUSTC_WRAPPER (and friends) exported by whoever launched the build does
/// not reach the compile. Control: the step builds, into the fresh target dir.
#[test]
fn a_callers_compiler_wrapper_does_not_reach_the_guest_builds_cargo() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, _) = begun(d.path());
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker);
    let mut c = gbe(&r);
    c.arg("cargo")
        .arg(&rec_path)
        .args(["--rustflags", CRT, "--"])
        .args(GUEST_INIT);
    for v in [
        "RUSTC_WRAPPER",
        "RUSTC_WORKSPACE_WRAPPER",
        "CARGO_BUILD_RUSTC_WRAPPER",
    ] {
        c.env(v, &w);
    }
    c.env("RUSTC", "/bin/false")
        .env("RUSTFLAGS", "--cfg evil")
        .env("CARGO_BUILD_RUSTC", "/bin/false");
    let b = c.output().unwrap();
    let rec: Value = serde_json::from_slice(&std::fs::read(&rec_path).unwrap()).unwrap();
    let built = gpath(&r, &rec_path, "axon-guest-init");
    let (ran, exists) = (marker.exists(), built.exists());
    discard(&rec);
    assert!(
        !ran,
        "ATTACK: a caller's RUSTC_WRAPPER reached the guest build's cargo:\n{}",
        text(&b)
    );
    assert!(
        b.status.success() && exists,
        "control: the controlled step builds, into the fresh target dir:\n{}",
        text(&b)
    );
}

/// The toolchain is the one rust-toolchain.toml pins, as rustup resolves it
/// under a CLEARED environment: a caller's RUSTUP_HOME holding a toolchain of
/// the same name does not choose the compiler. Control: the recorded rustc
/// is the invoking user's real toolchain.
#[test]
fn a_callers_rustup_home_does_not_choose_the_guest_toolchain() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let chan = std::fs::read_to_string(r.join("rust-toolchain.toml"))
        .unwrap()
        .lines()
        .find_map(|l| {
            l.trim().strip_prefix("channel").map(|v| {
                v.split('=')
                    .nth(1)
                    .unwrap()
                    .trim()
                    .trim_matches('"')
                    .to_string()
            })
        })
        .unwrap();
    let fake_home = d.path().join("fake-rustup");
    let bin = fake_home.join(format!("toolchains/{chan}-x86_64-unknown-linux-gnu/bin"));
    for tool in ["cargo", "rustc"] {
        write(
            &bin.join(tool),
            "#!/bin/sh\ncase \"$*\" in *config*) exit 0;; esac\necho \"fake 1.0 (planted)\"\n",
        );
        chmod_x(&bin.join(tool));
    }
    let out = d.path().join("out");
    let o = build_env_only(
        &r,
        &out,
        &[
            ("RUSTUP_HOME", fake_home.display().to_string()),
            ("RUSTUP_TOOLCHAIN", chan.clone()),
        ],
    );
    let rec = if o.status.success() {
        record(&out)
    } else {
        Value::Null
    };
    discard(&rec);
    let rustc = rec["toolchain"]["rustc"].as_str().unwrap_or("");
    assert!(
        !rustc.starts_with(fake_home.to_str().unwrap()),
        "ATTACK: a caller's RUSTUP_HOME chose the guest build's compiler ({rustc})"
    );
    assert!(
        o.status.success() && Path::new(rustc).is_file(),
        "control: the pinned toolchain resolves: {}",
        text(&o)
    );
}

/// Round 4b, finding 1: the build parent is refused unless only root or the
/// builder can write every ancestor -- a directory any uid can write (a
/// sticky /var/tmp included) is one where another uid plants a config cargo
/// reads. Control: the default parent, under the builder's home, begins
/// (every other test here).
#[test]
fn a_guest_build_under_a_directory_another_uid_can_write_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let scratch = private_scratch();
    let open = scratch.path().join("open");
    std::fs::create_dir_all(&open).unwrap();
    chmod(&open, 0o1777);
    let out = d.path().join("out");
    let o = build_env_only(
        &r,
        &out,
        &[(
            "AXON_GUEST_BUILD_PARENT",
            open.join("parent").display().to_string(),
        )],
    );
    if o.status.success() {
        discard(&record(&out));
    }
    assert!(
        !o.status.success(),
        "ATTACK: the guest build began under a directory any uid can write:\n{}",
        text(&o)
    );
    assert!(
        text(&o).contains("not private to the builder"),
        "{}",
        text(&o)
    );
}

/// Round 4b, finding 1, as the reviewer executed it: a `.cargo/config.toml`
/// naming a rustc wrapper, written into an ancestor of the CLONE after
/// `begin`, used to wrap every rustc of the next build. Cargo now runs in the
/// build's private copy, so the clone's ancestors are not where it looks.
/// Control: the step builds.
#[test]
fn an_ancestor_config_written_after_begin_does_not_reach_the_guest_build() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, rec) = begun(d.path());
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker);
    // An ancestor of the clone (the checkout), written AFTER begin.
    write(
        &d.path().join(".cargo/config.toml"),
        &format!("build.rustc-wrapper = \"{}\"\n", w.display()),
    );
    let b = gcargo(&r, &rec_path, Some(CRT), &GUEST_INIT);
    discard(&rec);
    assert!(
        !marker.exists(),
        "ATTACK: an ancestor config written after begin wrapped the guest build's rustc:\n{}",
        text(&b)
    );
    assert!(b.status.success(), "control: the step builds: {}", text(&b));
}

/// Round 4b, finding 1: cargo's effective config is held to begin's BEFORE
/// every invocation. A config placed (by the only uids that can) beside the
/// private copy after begin is refused before cargo starts, so its wrapper
/// never runs.
#[test]
fn a_cargo_config_planted_beside_the_private_copy_after_begin_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, rec) = begun(d.path());
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker);
    write(
        &base_of(&rec).join(".cargo/config.toml"),
        &format!("build.rustc-wrapper = \"{}\"\n", w.display()),
    );
    let b = gcargo(&r, &rec_path, Some(CRT), &GUEST_INIT);
    discard(&rec);
    assert!(
        !marker.exists(),
        "ATTACK: a cargo config planted after begin reached the guest build's compiler:\n{}",
        text(&b)
    );
    assert!(
        !b.status.success() && text(&b).contains("changed since begin"),
        "{}",
        text(&b)
    );
}

/// Round 4b, finding 1: and AFTER every invocation. A config that appears
/// while a step runs (here a build script writes one beside the private copy)
/// fails that step, and its record entry carries the differing check.
#[test]
fn a_cargo_config_written_during_a_guest_build_step_fails_that_step() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    write(
        &r.join("guest/build.rs"),
        "use std::path::PathBuf;\nfn main() {\n    let mut p = \
         PathBuf::from(std::env::var(\"OUT_DIR\").unwrap());\n    while \
         !p.join(\"cargo-home\").is_dir() {\n        if !p.pop() {\n            return;\n        \
         }\n    }\n    std::fs::create_dir_all(p.join(\".cargo\")).unwrap();\n    \
         std::fs::write(p.join(\".cargo/config.toml\"), \"[build]\\njobs = 1\\n\").unwrap();\n}\n",
    );
    git(&r, &["add", "-A"]);
    let out = d.path().join("out");
    let o = build_env_only(&r, &out, &[]);
    assert!(o.status.success(), "setup: {}", text(&o));
    let rec = record(&out);
    let b = gcargo(&r, &out.join("build-env.json"), Some(CRT), &GUEST_INIT);
    let written = base_of(&rec).join(".cargo/config.toml").exists();
    discard(&rec);
    assert!(written, "setup: the build script wrote the config");
    assert!(
        !b.status.success(),
        "ATTACK: a cargo config written during a guest build step left that step succeeded:\n{}",
        text(&b)
    );
    assert!(text(&b).contains("changed DURING"), "{}", text(&b));
}

/// Round 4b, finding 2: the step runs only an invocation in the table,
/// exactly. Extra RUSTFLAGS (a linker) or an extra `--config` naming a
/// wrapper is refused before cargo starts. Control: the exact invocation
/// builds (a_callers_compiler_wrapper_does_not_reach_the_guest_builds_cargo).
#[test]
fn a_guest_cargo_step_with_extra_flags_or_args_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, rec) = begun(d.path());
    let marker = d.path().join("wrapper-ran");
    let w = wrapper(d.path(), &marker);
    let wrap_cfg = format!("build.rustc-wrapper=\"{}\"", w.display());
    let mut with_config: Vec<&str> = GUEST_INIT.to_vec();
    with_config.splice(1..1, ["--config", wrap_cfg.as_str()]);
    let linker = format!("{CRT} -C linker={}", w.display());
    let cases: [(&str, &str, Vec<&str>); 3] = [
        ("a --config naming a rustc wrapper", CRT, with_config),
        (
            "extra RUSTFLAGS naming a linker",
            linker.as_str(),
            GUEST_INIT.to_vec(),
        ),
        (
            "a -Z flag",
            CRT,
            [GUEST_INIT.as_slice(), &["-Z", "unstable-options"]].concat(),
        ),
    ];
    for (attack, flags, args) in cases {
        let b = gcargo(&r, &rec_path, Some(flags), &args);
        assert!(
            !marker.exists() && !b.status.success(),
            "ATTACK: a guest cargo step outside its table ran ({attack}):\n{}",
            text(&b)
        );
        assert!(
            text(&b).contains("not a controlled guest build invocation"),
            "{attack}: {}",
            text(&b)
        );
    }
    discard(&rec);
}

/// Where the controlled build puts a musl release binary, as its own `path`
/// step answers (the production route, never a joined guess).
fn gpath(r: &Path, rec_path: &Path, name: &str) -> PathBuf {
    let o = gbe(r)
        .arg("path")
        .arg(rec_path)
        .args(["x86_64-unknown-linux-musl", "release", name])
        .output()
        .unwrap();
    assert!(o.status.success(), "setup: path: {}", text(&o));
    PathBuf::from(String::from_utf8_lossy(&o.stdout).trim())
}

/// Fake artifacts at the paths the controlled build would put them, `finish`ed
/// into the record (the rootfs step reads the record, not cargo).
fn finished(r: &Path, rec_path: &Path) {
    let mut pairs = vec![];
    for name in ["axon", "axon-guest-init", "axon-psv-runner"] {
        let p = gpath(r, rec_path, name);
        write(&p, &format!("#!/bin/sh\necho {name}\n"));
        pairs.push(format!("{name}={}", p.display()));
    }
    let o = gbe(r)
        .arg("finish")
        .arg(rec_path)
        .args(&pairs)
        .output()
        .unwrap();
    assert!(o.status.success(), "setup: finish: {}", text(&o));
}

/// Round 4b, finding 3: the rootfs is assembled only from the bytes the
/// controlled build recorded. A binary replaced after the build is refused.
/// Control: the recorded bytes assemble, and the record names the output.
#[test]
fn a_rootfs_from_a_binary_the_controlled_build_did_not_produce_is_refused() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, _) = begun(d.path());
    finished(&r, &rec_path);
    let runner = gpath(&r, &rec_path, "axon-psv-runner");
    let honest = std::fs::read(&runner).unwrap();
    std::fs::write(&runner, b"#!/bin/sh\necho forged runner\n").unwrap();
    let sq = d.path().join("rootfs.sqfs");
    let o = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .output()
        .unwrap();
    std::fs::write(&runner, honest).unwrap();
    assert!(
        !o.status.success(),
        "ATTACK: the rootfs was assembled from a binary the controlled build did not produce:\n{}",
        text(&o)
    );
    assert!(text(&o).contains("is not the bytes"), "{}", text(&o));
    let c = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .output()
        .unwrap();
    let after: Value = serde_json::from_slice(&std::fs::read(&rec_path).unwrap()).unwrap();
    discard(&after);
    assert!(
        c.status.success(),
        "control: the rootfs assembles: {}",
        text(&c)
    );
    assert_eq!(
        after["rootfs"]["sha256"],
        sha(&sq),
        "control: output recorded"
    );
    assert_eq!(after["rootfs"]["tool"]["path"], "/usr/bin/mksquashfs");
}

/// Round 4b, finding 3: the rootfs is made by /usr/bin/mksquashfs under a
/// constructed environment, never one on the caller's PATH; the busybox
/// installed is the pinned one (its COPY verified). Control: the step
/// succeeds with the planted PATH.
#[test]
fn a_callers_mksquashfs_or_busybox_does_not_make_the_rootfs() {
    let d = tempfile::tempdir().unwrap();
    let (r, rec_path, rec) = begun(d.path());
    finished(&r, &rec_path);
    let evil = d.path().join("evil-bin");
    let marker = d.path().join("evil-mksquashfs-ran");
    // Writes the output it is asked for, so nothing else in the step refuses.
    write(
        &evil.join("mksquashfs"),
        &format!(
            "#!/bin/sh\n: > '{}'\nprintf forged > \"$2\"\n",
            marker.display()
        ),
    );
    chmod_x(&evil.join("mksquashfs"));
    let sq = d.path().join("rootfs.sqfs");
    let path = format!("{}:{}", evil.display(), std::env::var("PATH").unwrap());
    let o = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .env("PATH", &path)
        .output()
        .unwrap();
    assert!(
        !marker.exists(),
        "ATTACK: a mksquashfs on the caller's PATH made the rootfs:\n{}",
        text(&o)
    );
    assert!(
        o.status.success(),
        "control: the rootfs assembles: {}",
        text(&o)
    );
    // The pinned busybox's bytes changed after the pin: refused.
    let bb = d.path().join("busybox");
    std::fs::write(&bb, "#!/bin/sh\necho sh\necho forged\n").unwrap();
    let o = gbe(&r)
        .arg("rootfs")
        .arg(&rec_path)
        .arg(&sq)
        .output()
        .unwrap();
    discard(&rec);
    assert!(
        !o.status.success(),
        "ATTACK: the rootfs installed a busybox that is not the pinned one:\n{}",
        text(&o)
    );
    assert!(text(&o).contains("busybox sha256 mismatch"), "{}", text(&o));
}

/// A kernel "source tarball" whose Makefile writes into vmlinux what its
/// recipe sees of the variables a caller could use to steer the compiler.
fn kernel_fixture(d: &Path) -> (PathBuf, PathBuf) {
    let src = d.join("ksrc/linux-0.0.1");
    write(
        &src.join("Makefile"),
        "olddefconfig:\n\t@true\nvmlinux:\n\t@printf 'kcflags=[%s] cc=[%s] cross=[%s] path=[%s]\\n' \
         \"$$KCFLAGS\" \"$(CC)\" \"$$CROSS_COMPILE\" \"$$PATH\" > vmlinux\n",
    );
    let dist = d.join("dist");
    std::fs::create_dir_all(&dist).unwrap();
    let st = Command::new("/usr/bin/tar")
        .arg("-C")
        .arg(d.join("ksrc"))
        .arg("-cJf")
        .arg(dist.join("linux-0.0.1.tar.xz"))
        .arg("linux-0.0.1")
        .status()
        .unwrap();
    assert!(st.success(), "setup: tar");
    let prof = d.join("prof");
    write(&prof.join("k.config"), "CONFIG_A=y\n");
    write(&prof.join("o.config"), "# overlay\nCONFIG_B=y\n");
    write(
        &prof.join("kernel.pin"),
        &format!(
            "KERNEL_VERSION=0.0.1\nKERNEL_TARBALL_SHA256={}\nKERNEL_CONFIG=k.config\n\
             KERNEL_CONFIG_SHA256={}\nKERNEL_OVERLAY=o.config\nKERNEL_OVERLAY_SHA256={}\n",
            sha(&dist.join("linux-0.0.1.tar.xz")),
            sha(&prof.join("k.config")),
            sha(&prof.join("o.config"))
        ),
    );
    (dist, prof)
}

fn kernel_step(r: &Path, dist: &Path, prof: &Path, env: &[(&str, String)]) -> Output {
    let mut c = gbe(r);
    c.arg("kernel")
        .arg(dist.join("kernel-build.json"))
        .arg(dist)
        .arg(prof);
    for (k, v) in env {
        c.env(k, v);
    }
    c.output().unwrap()
}

/// Round 4b, finding 3: the kernel's make runs in a constructed environment.
/// KCFLAGS, CC, CROSS_COMPILE and a PATH with a planted gcc/make exported by
/// whoever launched the build do not reach it. Control: vmlinux is built, and
/// the record names /usr/bin/make and the host gcc with digests.
#[test]
fn a_callers_kcflags_cc_or_path_do_not_reach_the_kernel_build() {
    let d = tempfile::tempdir().unwrap();
    let r = checkout(d.path());
    let (dist, prof) = kernel_fixture(d.path());
    let evil = d.path().join("evil-bin");
    for t in ["make", "gcc", "cc"] {
        write(&evil.join(t), "#!/bin/sh\nexit 0\n");
        chmod_x(&evil.join(t));
    }
    let path = format!("{}:{}", evil.display(), std::env::var("PATH").unwrap());
    let o = kernel_step(
        &r,
        &dist,
        &prof,
        &[
            ("KCFLAGS", "-DEVIL".into()),
            ("CC", "/tmp/evil-cc".into()),
            ("CROSS_COMPILE", "evil-".into()),
            ("PATH", path),
        ],
    );
    assert!(
        o.status.success(),
        "control: the kernel builds: {}",
        text(&o)
    );
    let vml = std::fs::read_to_string(dist.join("vmlinux")).unwrap();
    assert!(
        !vml.to_lowercase().contains("evil"),
        "ATTACK: a caller's KCFLAGS/CC/CROSS_COMPILE/PATH reached the kernel build: {vml}"
    );
    let k: Value =
        serde_json::from_slice(&std::fs::read(dist.join("kernel-build.json")).unwrap()).unwrap();
    assert_eq!(k["tools"]["make"]["path"], "/usr/bin/make");
    assert!(k["tools"]["gcc"]["sha256"]
        .as_str()
        .is_some_and(|s| s.len() == 64));
    assert_eq!(k["vmlinux_sha256"], sha(&dist.join("vmlinux")));
}

/// Round 4b, finding 3: the kernel is built only from the pinned tarball,
/// config and overlay, each verified as the COPY the build then uses.
/// Control: a_callers_kcflags_cc_or_path_do_not_reach_the_kernel_build.
#[test]
fn a_kernel_from_sources_that_are_not_the_pinned_ones_is_refused() {
    for (attack, file) in [
        (
            "a tarball that is not the pinned one",
            "dist/linux-0.0.1.tar.xz",
        ),
        ("a config that is not the pinned one", "prof/k.config"),
        ("an overlay that is not the pinned one", "prof/o.config"),
    ] {
        let d = tempfile::tempdir().unwrap();
        let r = checkout(d.path());
        let (dist, prof) = kernel_fixture(d.path());
        if file.ends_with(".tar.xz") {
            // Another well-formed tarball, so only the pin can refuse it.
            let mk = d.path().join("ksrc/linux-0.0.1/Makefile");
            let s = std::fs::read_to_string(&mk).unwrap();
            write(&mk, &format!("# not the pinned source\n{s}"));
            let st = Command::new("/usr/bin/tar")
                .arg("-C")
                .arg(d.path().join("ksrc"))
                .arg("-cJf")
                .arg(dist.join("linux-0.0.1.tar.xz"))
                .arg("linux-0.0.1")
                .status()
                .unwrap();
            assert!(st.success(), "setup: tar");
        } else {
            let p = d.path().join(file);
            let mut b = std::fs::read(&p).unwrap();
            b.extend_from_slice(b"CONFIG_C=y\n");
            std::fs::write(&p, b).unwrap();
        }
        let o = kernel_step(&r, &dist, &prof, &[]);
        assert!(
            !o.status.success(),
            "ATTACK: the kernel was built from {attack}:\n{}",
            text(&o)
        );
        assert!(
            text(&o).contains("sha256 mismatch"),
            "{attack}: {}",
            text(&o)
        );
    }
}
