//! R14 mobile (`--host mobile`) build support: the deterministic wrapper
//! generator + the Android `jniLibs/` packaging layout.
//!
//! Per spec §3/§4/Q2 the wrapper is **two parts**:
//!   * a hand-written, versioned `AxonRuntime` lifecycle bridge (Kotlin/Swift,
//!     in the TCB) — NOT generated here; it lives in the platform support lib;
//!   * a tiny GENERATED per-app `@main` shim (~10 lines) that binds this app's
//!     exported C-ABI entry names (`on_start`/`on_frame`/`on_resume`) into the
//!     bridge.
//!
//! This module owns the generated shim. The generator is **deterministic** (a
//! pure function of `MobileEntries` + the lib name), so the golden test
//! `mobile_wrapper_is_byte_stable` can assert byte-stability — and a
//! self-improving pass cannot inject native code into it (I-12: it is a fixed
//! template, not AI-authored).
//!
//! Slice 2 ships the Android (Kotlin) generator. iOS (Swift) is specified but
//! gated on a macOS host (§4 / Q4); the Swift generator is provided in the same
//! deterministic shape so an iOS host can use it without new design, but it is
//! never the default on this Linux host.

use crate::ast::{Item, Program};

/// The exported C-ABI entry names a mobile app binds into the runtime bridge.
///
/// `start` is required (the app's main entry); `frame`/`resume` are optional
/// (an app with no frame loop / no lifecycle just omits them). Resolved from
/// the program by [`MobileEntries::from_program`].
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct MobileEntries {
    pub start: Option<String>,
    pub frame: Option<String>,
    pub resume: Option<String>,
}

impl MobileEntries {
    /// Resolve the lifecycle entry names from `@[entry]`/`@[frame]`/`@[resume]`
    /// attributes, falling back to the conventional names (`on_start`,
    /// `on_frame`, `on_resume`) or `main` when none is annotated.
    pub fn from_program(program: &Program) -> Self {
        let mut e = MobileEntries::default();
        let mut has_main = false;
        let mut has_on_start = false;
        for item in &program.items {
            if let Item::FnDef(f) = item {
                if f.name == "main" {
                    has_main = true;
                }
                if f.name == "on_start" {
                    has_on_start = true;
                }
                if f.name == "on_frame" && e.frame.is_none() {
                    e.frame = Some("on_frame".to_string());
                }
                if f.name == "on_resume" && e.resume.is_none() {
                    e.resume = Some("on_resume".to_string());
                }
                for a in &f.attrs {
                    match a.name.as_str() {
                        "entry" => e.start = Some(f.name.clone()),
                        "frame" => e.frame = Some(f.name.clone()),
                        "resume" => e.resume = Some(f.name.clone()),
                        _ => {}
                    }
                }
            }
        }
        if e.start.is_none() {
            e.start = if has_on_start {
                Some("on_start".to_string())
            } else if has_main {
                Some("main".to_string())
            } else {
                None
            };
        }
        e
    }
}

/// Generate the deterministic Android Kotlin `@main` shim for `lib`
/// (the `.so` base name, e.g. `app` for `libapp.so`) and `entries`.
///
/// The shim is intentionally minimal (the "~50 lines" budget, §9): it loads the
/// native lib, declares the `external fun` bindings for the exported entries,
/// and registers them with the hand-written `AxonRuntime` bridge. The run loop
/// lives in `AxonRuntime`, not here.
pub fn generate_kotlin_wrapper(lib: &str, entries: &MobileEntries) -> String {
    let mut s = String::new();
    s.push_str("// Generated by `axon target build --host mobile` — DO NOT EDIT.\n");
    s.push_str("// The hand-written AxonRuntime lifecycle bridge owns the Android\n");
    s.push_str("// Activity run loop and calls these entries (R14 §3/§4, Q2).\n");
    s.push_str("package dev.axon.app\n\n");
    s.push_str("import dev.axon.runtime.AxonRuntime\n");
    s.push_str("import dev.axon.runtime.AxonEntries\n\n");
    s.push_str("object AxonApp {\n");
    s.push_str(&format!("    init {{ System.loadLibrary(\"{lib}\") }}\n\n"));

    // External bindings for each present entry. The C-ABI entries take/return
    // i64 (the frozen scalar ABI); the bridge marshals lifecycle state.
    let emit_extern = |s: &mut String, name: &str| {
        s.push_str(&format!("    external fun {name}(arg: Long): Long\n"));
    };
    if let Some(ref n) = entries.start {
        emit_extern(&mut s, n);
    }
    if let Some(ref n) = entries.frame {
        emit_extern(&mut s, n);
    }
    if let Some(ref n) = entries.resume {
        emit_extern(&mut s, n);
    }
    s.push('\n');

    // Register the entry table with the bridge.
    s.push_str("    val entries = AxonEntries(\n");
    s.push_str(&format!(
        "        start = {},\n",
        kt_lambda(entries.start.as_deref())
    ));
    s.push_str(&format!(
        "        frame = {},\n",
        kt_lambda(entries.frame.as_deref())
    ));
    s.push_str(&format!(
        "        resume = {}\n",
        kt_lambda(entries.resume.as_deref())
    ));
    s.push_str("    )\n\n");
    s.push_str("    fun launch() = AxonRuntime.run(entries)\n");
    s.push_str("}\n");
    s
}

fn kt_lambda(name: Option<&str>) -> String {
    match name {
        Some(n) => format!("{{ a -> {n}(a) }}"),
        None => "null".to_string(),
    }
}

/// Map an Android LLVM triple to its `jniLibs/<abi>/` directory name.
///
/// Returns `None` for a non-Android or unrecognized triple.
pub fn android_jni_abi(triple: &str) -> Option<&'static str> {
    if !triple.contains("-android") {
        return None;
    }
    if triple.starts_with("aarch64") {
        Some("arm64-v8a")
    } else if triple.starts_with("x86_64") {
        Some("x86_64")
    } else if triple.starts_with("armv7") || triple.starts_with("arm-") {
        Some("armeabi-v7a")
    } else if triple.starts_with("i686") {
        Some("x86")
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn jni_abi_mapping() {
        assert_eq!(android_jni_abi("aarch64-linux-android"), Some("arm64-v8a"));
        assert_eq!(android_jni_abi("x86_64-linux-android"), Some("x86_64"));
        assert_eq!(
            android_jni_abi("armv7-linux-androideabi"),
            Some("armeabi-v7a")
        );
        assert_eq!(android_jni_abi("aarch64-apple-ios"), None);
        assert_eq!(android_jni_abi("x86_64-unknown-linux-gnu"), None);
    }

    #[test]
    fn wrapper_is_byte_stable_golden() {
        // The golden — a fixed entry set must produce a fixed wrapper, twice.
        let entries = MobileEntries {
            start: Some("on_start".to_string()),
            frame: Some("on_frame".to_string()),
            resume: Some("on_resume".to_string()),
        };
        let a = generate_kotlin_wrapper("app", &entries);
        let b = generate_kotlin_wrapper("app", &entries);
        assert_eq!(a, b, "generator must be deterministic");

        // Byte-stable golden (regenerate intentionally if the template changes).
        let golden = "\
// Generated by `axon target build --host mobile` — DO NOT EDIT.
// The hand-written AxonRuntime lifecycle bridge owns the Android
// Activity run loop and calls these entries (R14 §3/§4, Q2).
package dev.axon.app

import dev.axon.runtime.AxonRuntime
import dev.axon.runtime.AxonEntries

object AxonApp {
    init { System.loadLibrary(\"app\") }

    external fun on_start(arg: Long): Long
    external fun on_frame(arg: Long): Long
    external fun on_resume(arg: Long): Long

    val entries = AxonEntries(
        start = { a -> on_start(a) },
        frame = { a -> on_frame(a) },
        resume = { a -> on_resume(a) }
    )

    fun launch() = AxonRuntime.run(entries)
}
";
        assert_eq!(a, golden, "wrapper diverged from golden");

        // The "~50 lines" budget (§9, ≤80 with headroom).
        assert!(
            a.lines().count() <= 80,
            "generated wrapper exceeds 80 lines: {}",
            a.lines().count()
        );
    }

    #[test]
    fn missing_entries_emit_null_lambdas() {
        let entries = MobileEntries {
            start: Some("main".to_string()),
            frame: None,
            resume: None,
        };
        let w = generate_kotlin_wrapper("compute", &entries);
        assert!(w.contains("external fun main(arg: Long): Long"));
        assert!(w.contains("frame = null"));
        assert!(w.contains("resume = null"));
        assert!(!w.contains("external fun on_frame"));
    }
}
