//! R7c Slice 2 — `browser_pure_compute_parity`: the load-bearing acceptance test.
//!
//! The Axon INTERPRETER compiled to `wasm32-unknown-unknown` runs pure-compute
//! `.ax` programs in REAL headless Chrome (via `wasm-bindgen-test`) and returns a
//! result BYTE-IDENTICAL to the native/interp oracle. This is invariant I-2
//! (parity) extended with a third comparison column — the browser — exactly as
//! `wasm_parity.sh` does for wasmtime.
//!
//! HOW IT STAYS HONEST (no hidden oracle): the parity SCRIPT
//! (`scripts/browser_compute_parity.sh`) runs each program through the NATIVE
//! `axon run` first, captures `(exit_code, stdout)`, and writes them into a
//! generated `oracle.rs` table that this test `include!`s. The wasm side then
//! asserts the wasm `axon_eval` exit code + captured stdout equal the native
//! oracle. If native and wasm ever diverge, the assertion fires. The generated
//! file is git-ignored and regenerated each run, so the oracle is always the
//! live native result — never a stale hand-copied constant.
//!
//! Run it headlessly:  `bash scripts/browser_compute_parity.sh`
//! (installs nothing; SKIP-guards if chrome/chromedriver/the wasm target are
//! absent so the default `gate.sh` is safe — but on a host WITH headless Chrome
//! it actually runs and asserts.)

#![cfg(target_arch = "wasm32")]

use wasm_bindgen_test::*;

wasm_bindgen_test_configure!(run_in_browser);

// Satisfy axon-core's `extern "C" { fn axon_host_await(...) }` import (the R15
// browser host_await binding) at LINK time. Without a definition, rust-lld leaves
// it as an `env.axon_host_await` wasm IMPORT; wasm-bindgen then turns that into an
// unsatisfiable JS `import 'env'`, which CRASHES Chrome's renderer on instantiate
// (the SIGKILL we hit before adding this). In the REAL browser bundle the page's
// JS supplies this import (R15 §13 B3); in the test there is no page driver, and
// the compute-only corpus never calls host_await — so a defined no-op (returning
// -1 = end-of-input) makes the module instantiate cleanly. This is test-only: the
// shipped axon-wasm cdylib still imports it for the page to provide.
#[no_mangle]
pub extern "C" fn axon_host_await(
    _req_ptr: *const u8,
    _req_len: usize,
    _out_ptr: *mut u8,
    _out_cap: usize,
) -> i64 {
    -1
}

// The native-oracle table: `ORACLE: &[(name, source, expect_exit, expect_out)]`,
// generated by scripts/browser_compute_parity.sh (written next to this file as
// `oracle.rs`, git-ignored) BEFORE the test runs. A committed fallback `oracle.rs`
// with a tiny corpus keeps the test compilable without the script; the script
// overwrites it with the live native oracle for the full corpus.
include!("oracle.rs");

/// Drive one program through the wasm interpreter's C-ABI exactly as JS would:
/// alloc → write source → eval → read back captured stdout. Returns
/// `(exit_code, stdout)`.
fn run_via_wasm_abi(src: &str) -> (i32, String) {
    let bytes = src.as_bytes();
    let len = bytes.len();
    unsafe {
        let p = axon_wasm::axon_alloc(len);
        // Copy the source into the wasm linear-memory buffer axon_alloc handed us.
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), p, len);
        let code = axon_wasm::axon_eval(p, len);
        let out_ptr = axon_wasm::axon_output_ptr();
        let out_len = axon_wasm::axon_output_len();
        let out = std::slice::from_raw_parts(out_ptr, out_len);
        (code, String::from_utf8_lossy(out).into_owned())
    }
}

#[wasm_bindgen_test]
fn browser_pure_compute_parity() {
    assert!(
        !ORACLE.is_empty(),
        "browser_pure_compute_parity: empty oracle — run via scripts/browser_compute_parity.sh"
    );
    let mut ran = 0;
    for (name, src, expect_exit, expect_out) in ORACLE {
        let (code, out) = run_via_wasm_abi(src);
        assert_eq!(
            code, *expect_exit,
            "{name}: wasm exit {code} != native oracle {expect_exit}"
        );
        assert_eq!(
            out, *expect_out,
            "{name}: wasm stdout != native oracle\n  wasm:   {out:?}\n  native: {expect_out:?}"
        );
        ran += 1;
    }
    assert!(ran > 0, "no programs ran — corpus missing");
}

/// The literal spec acceptance: a program that RETURNS 42 returns 42 in the tab
/// (the spec's headline phrasing, §9). Embedded directly so it runs even if the
/// generated corpus is reduced.
#[wasm_bindgen_test]
fn browser_returns_42() {
    let src = "fn main() -> i64 { 42 }\n";
    let (code, _out) = run_via_wasm_abi(src);
    assert_eq!(
        code, 42,
        "a program returning 42 must return 42 in the browser"
    );
}

/// Adversarial (spec §8): an ungranted `read_file` under the browser host returns
/// an `Err` surfaced as program output — never a wasm trap that takes down the
/// tab (I-4). The wasm BrowserHost (DefaultHost on wasm) read_file hits no real
/// fs, so the Result is `Err`; the program handles it and exits cleanly.
#[wasm_bindgen_test]
fn browser_host_fs_returns_err_not_trap() {
    // read_file returns Result<str,str>; match it. An ungranted path yields Err,
    // and the program returns 7 — a clean exit, NOT a trap. If read_file trapped,
    // axon_eval would never return and the test would hang/abort.
    let src =
        "fn main() -> i64 { match read_file(\"/nope/missing.txt\") { Ok(_) => 0  Err(_) => 7 } }\n";
    let (code, _out) = run_via_wasm_abi(src);
    assert_eq!(
        code, 7,
        "ungranted read_file must surface Err (exit 7), not trap the tab"
    );
}
