#!/usr/bin/env bash
# browser_compute_parity.sh — R7c Slice 2, the LOAD-BEARING acceptance gate.
#
# Runs the Axon INTERPRETER (wasm32-unknown-unknown) in REAL headless Chrome via
# wasm-bindgen-test and asserts every pure-compute program returns a result
# BYTE-IDENTICAL to the native `axon run` oracle (exit code + stdout). This is
# invariant I-2 (parity) with the browser as a third comparison column.
#
# The oracle is LIVE: this script runs each program through native first and bakes
# (exit, stdout) into crates/axon-wasm/tests/oracle.rs, which the wasm test
# include!s — so the wasm side is compared against the real native result, never a
# stale constant. The test (browser_compute_parity.rs) also runs the spec headline
# (a program returning 42 returns 42) and the adversarial case (ungranted
# read_file → Err, not a tab-killing trap).
#
# SKIP-GUARDED (exit 0) if the wasm target / Chrome / a matching chromedriver /
# wasm-bindgen-test-runner are absent, so the DEFAULT gate.sh stays green on a
# host without a browser. On a host WITH headless Chrome it ACTUALLY RUNS and the
# assertions are real. To force-fail instead of skip when a dep is missing, set
# BROWSER_PARITY_REQUIRE=1.
set -u

# AUDIT O004: take the SHARED wasm build lock. Several of these harnesses build
# for wasm32 concurrently under cargo's parallel test threads and clobber each
# other's intermediates, which surfaces as examples silently failing to link.
# Nine harnesses already took this lock; this one did not, so it raced against
# them. No-op without flock.
if command -v flock >/dev/null 2>&1; then exec 9>"${TMPDIR:-/tmp}/axon_wasm_parity.lock" && flock 9; fi


ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# This is a HEAVY harness — it builds the ~20 MB interpreter wasm and drives a
# real headless Chrome (minutes). To keep `gate.sh --strict` / parity_all.sh fast
# and not couple them to a browser toolchain, it is OPT-IN: skip (exit 0) unless
# BROWSER_PARITY=1 is set. The dedicated invocation `BROWSER_PARITY=1 bash
# scripts/browser_compute_parity.sh` is the gate-verified path (R7c §9 Slice 2).
if [ "${BROWSER_PARITY:-0}" != "1" ]; then
  echo "browser_compute_parity: opt-in harness — skipping (set BROWSER_PARITY=1 to run in headless Chrome)"
  exit 0
fi

require_or_skip() {
  # $1 = human reason
  if [ "${BROWSER_PARITY_REQUIRE:-0}" = "1" ]; then
    echo "browser_compute_parity: FAIL (BROWSER_PARITY_REQUIRE=1) — $1"; exit 1
  fi
  echo "browser_compute_parity: $1 — skipping (set BROWSER_PARITY_REQUIRE=1 to force-fail)"; exit 0
}

# ── Dependency probes ────────────────────────────────────────────────────────
if ! rustup target list --installed 2>/dev/null | grep -q wasm32-unknown-unknown; then
  require_or_skip "wasm32-unknown-unknown target not installed (rustup target add wasm32-unknown-unknown)"
fi

CHROME_BIN="${CHROME:-$(command -v google-chrome || command -v google-chrome-stable || command -v chromium || true)}"
[ -n "$CHROME_BIN" ] || require_or_skip "no Chrome/Chromium on PATH (set CHROME=...)"

# A chromedriver matching the installed Chrome is required by wasm-bindgen-test.
CHROMEDRIVER_BIN="${CHROMEDRIVER:-$(command -v chromedriver || true)}"
[ -n "$CHROMEDRIVER_BIN" ] || require_or_skip "no chromedriver (CHROMEDRIVER=... ; match the Chrome major version)"

command -v wasm-bindgen-test-runner >/dev/null 2>&1 \
  || require_or_skip "wasm-bindgen-test-runner not on PATH (cargo install wasm-bindgen-cli)"

# ── Build native axon (oracle producer) ──────────────────────────────────────
echo "browser_compute_parity: building native axon (oracle)…"
cargo build -q -p axon-core --no-default-features --bin axon 2>/dev/null \
  || { echo "browser_compute_parity: native build failed"; exit 1; }
NATIVE="target/debug/axon"

# ── Generate the live native oracle table → tests/oracle.rs ──────────────────
# Compute-only corpus: no host fs/ai/random/time/host_await — the cases the wasm
# interpreter runs identically with no host binding. (Matches the corpus in
# wasm_browser_interp_parity.sh.)
PROGS=(
  examples/hello.ax
  examples/math.ax
  examples/algorithms.ax
  examples/structs.ax
  examples/enums.ax
  examples/while.ax
  examples/options.ax
  examples/modulo.ax
)
ORACLE_RS="crates/axon-wasm/tests/oracle.rs"
TMP_ORACLE="$(mktemp)"; trap 'rm -f "$TMP_ORACLE"' EXIT

{
  echo "// GENERATED by scripts/browser_compute_parity.sh — DO NOT EDIT BY HAND."
  echo "// Live native-oracle table (name, .ax source, exit code, stdout)."
  echo "#[allow(clippy::type_complexity)]"
  echo "static ORACLE: &[(&str, &str, i32, &str)] = &["
} > "$TMP_ORACLE"

count=0
for p in "${PROGS[@]}"; do
  [ -f "$p" ] || continue
  out="$("$NATIVE" run "$p" 2>/dev/null)"; code=$?
  name="$(basename "$p")"
  # Escape source + output into Rust string literals via python (handles all of
  # \, ", newline, and any UTF-8). printf %s avoids trailing-newline mangling.
  # ensure_ascii=False keeps UTF-8 chars literal — Rust string literals accept raw
  # UTF-8 but REJECT Python's `\uXXXX` form (it wants `\u{XXXX}`). json.dumps still
  # escapes \, ", and control chars correctly, which is all Rust needs.
  esc_src="$(python3 -c 'import sys,json; print(json.dumps(open(sys.argv[1]).read(), ensure_ascii=False))' "$p")"
  # `axon run` output captured via $() strips ONE trailing newline; the wasm
  # captured output preserves it, so re-add exactly one to match the program.
  esc_out_nl="$(printf '%s\n' "$out" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read(), ensure_ascii=False))')"
  printf '    (%s, %s, %d, %s),\n' "\"$name\"" "$esc_src" "$code" "$esc_out_nl" >> "$TMP_ORACLE"
  count=$((count + 1))
done
echo "];" >> "$TMP_ORACLE"

if [ "$count" -eq 0 ]; then
  echo "browser_compute_parity: FAIL — corpus empty (no example programs found)"; exit 1
fi
cp "$TMP_ORACLE" "$ORACLE_RS"
echo "browser_compute_parity: generated oracle for $count programs → $ORACLE_RS"

# ── Run the wasm-bindgen test in headless Chrome ─────────────────────────────
# wasm-bindgen-test reads the Chrome capabilities (--headless=new --no-sandbox
# --disable-dev-shm-usage …) from crates/axon-wasm/webdriver.json. CHROMEDRIVER
# points it at the matching driver; the test wasm is built in RELEASE (a ~20 MB
# debug wasm overran Chrome's load/instantiate budget and was SIGKILLed — the
# release wasm loads well within the timeout).
export CHROMEDRIVER="$CHROMEDRIVER_BIN"
export WASM_BINDGEN_TEST_TIMEOUT="${WASM_BINDGEN_TEST_TIMEOUT:-300}"

echo "browser_compute_parity: running wasm-bindgen-test in headless Chrome (release)…"
echo "  CHROME=$CHROME_BIN"
echo "  CHROMEDRIVER=$CHROMEDRIVER_BIN"

# Capture output so we can assert the test actually RAN (a skipped/0-test run must
# FAIL, not pass vacuously).
LOG="$(mktemp)"; trap 'rm -f "$TMP_ORACLE" "$LOG"' EXIT
set -o pipefail
CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER="wasm-bindgen-test-runner" \
  cargo test --release -p axon-wasm --target wasm32-unknown-unknown \
    --test browser_compute_parity 2>&1 | grep -viE "\[DEBUG\]|DevTools|^\s+\"" | tee "$LOG"
status=${PIPESTATUS[0]}
set +o pipefail

if [ "$status" -ne 0 ]; then
  echo "browser_compute_parity: FAIL — wasm-bindgen test run returned $status"
  exit 1
fi

# Vacuous-pass guard: require evidence the tests actually executed in the browser.
if ! grep -qiE "test result: ok|[1-9][0-9]* (passed|tests? passed)" "$LOG"; then
  echo "browser_compute_parity: FAIL — no test-result line; the browser test did not run"
  exit 1
fi

# Confirm all three test functions ran (parity + returns_42 + fs_err).
ran="$(grep -oiE "[0-9]+ passed" "$LOG" | grep -oE "[0-9]+" | head -1 || echo 0)"
if [ "${ran:-0}" -lt 1 ]; then
  echo "browser_compute_parity: FAIL — 0 browser tests passed"; exit 1
fi

echo "browser_compute_parity: PASS — $ran browser test(s) green in headless Chrome; wasm interpreter == native oracle over $count programs"
exit 0
